### PR TITLE
Fix multi-contact on rigidbody distro

### LINKED ISSUE #1035: multiContactTest fails on rigidbody distro
saw this on the nightly builds for both on drake002 (/tmp/drake-rigidbody/drake-13103) and drake001(/tmp/drake-rigidbody/drake-4774)

```
systems/plants/test/multiContactTest (unknown issue)
```
error_id = Simulink:SFunctions:SFcnErrorStatus
error_message = Error reported by S-function 'DCSFunction' in
'TimeSteppingRigidBodyManipulator_063597076501216552/DrakeSys':

DrakeSystem S-Function: error MATLAB:innerdim in MATLAB callback.
See additional debugging information above
is_segfault = 0
```
```Matlab

                           < M A T L A B (R) >
                 Copyright 1984-2014 The MathWorks, Inc.
                   R2014a (8.3.0.532) 64-bit (glnxa64)
                            February 11, 2014


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

To reproduce this test use rng(1008564700,'twister')

[Warning: Disabling autosave for simulink blocks (to avoid generating a
lot of
*.mdl.autosave files in your directory.  If you aren't a regular Simulink
user
and don't want this disabled, comment out this section in addpath_drake.
To disable this warning in the future, add
  warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m] 
[> In addpath_drake at 74
 In addpath_drake at 4] 
Added the lcm jar to your javaclasspath (found via cmake)
[Warning: Currently all of your LCM traffic will be broadcast to the
network,
because:
/tmp/drake-rigidbody/drake-13103/util/check_multicast_is_loopback.sh: line
3:
ifconfig: command not found
/tmp/drake-rigidbody/drake-13103/util/check_multicast_is_loopback.sh: line
6:
ifconfig: command not found
 Loopback interface is not set to multicast.
 Consider running: sudo
 /tmp/drake-rigidbody/drake-13103/util/setup_loopback_multicast.sh
] 
[> In checkDependency at 74
 In checkDependency at 85
 In multiContactTest at 3
 In fevalPackageSafe at 21] 
Added the lcmgl jar to your javaclasspath (found via cmake)
LCM: Disabling IPV6 support
LCM: TTL set to zero, traffic will not leave localhost.

ans =

    1

Cannot find required pod snopt
DrakeSystem S-Function: error when calling ''update'' with the following
arguments:
 TimeSteppingRigidBodyManipulator with properties:

                     timestep: 0.0100
                         twoD: 0
             position_control: 0
                    LCP_cache: [1x1 SharedDataHandle]
                enable_fastqp: 0
   lcmgl_contact_forces_scale: 0
         z_inactive_guess_tol: 0.0100
            multiple_contacts: 1
               gurobi_present: 0
                         umin: [0x1 double]
                         umax: [0x1 double]
              warning_manager: [1x1 WarningManager]

    0

        0
        0
   1.5000
        0
        0
        0
        0
        0
   3.5000
        0
        0
   1.5708
        0
   0.7500
   6.5000
        0
        0
        0
        0
  -0.7500
   6.5000
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0
        0

Error using *
Inner matrix dimensions must agree.

Error in TimeSteppingRigidBodyManipulator/solveLCP (line 378)
           possible_contact_indices = (phiC+h*n*qd) <
obj.z_inactive_guess_tol;

Error in TimeSteppingRigidBodyManipulator/update (line 198)
         [obj,z,Mqdn,wqdn] = solveLCP(obj,t,x,u);

Error in SimulinkModelHandle/sim (line 110)
     varargout{:} = sim(obj.name,varargin{:});

Error in DynamicalSystem/simulate (line 108)
simout = sim(mdl,pstruct);

Error in DrakeSystem/simulate (line 489)
       [varargout{:}] = simulate@DynamicalSystem(obj,varargin{:});

Error in multiContactTest (line 25)
 xtraj = p.simulate([0 3], [q0;q1;q2;q3;0*q0;0*q1;0*q2;0*q3]);

Error in fevalPackageSafe (line 21)
 feval(f);
Error using SimulinkModelHandle/sim (line 110)
Error reported by S-function 'DCSFunction' in
'TimeSteppingRigidBodyManipulator_063597076501216552/DrakeSys':


DrakeSystem S-Function: error MATLAB:innerdim in MATLAB callback.
See additional debugging information above

Error in DynamicalSystem/simulate (line 108)
simout = sim(mdl,pstruct);

Error in DrakeSystem/simulate (line 489)
       [varargout{:}] = simulate@DynamicalSystem(obj,varargin{:});

Error in multiContactTest (line 25)
 xtraj = p.simulate([0 3], [q0;q1;q2;q3;0*q0;0*q1;0*q2;0*q3]);

Error in fevalPackageSafe (line 21)
 feval(f);


<test_name>systems/plants/test/multiContactTest</test_name>
<error_id>Simulink:SFunctions:SFcnErrorStatus</error_id>
<error_message>Error reported by S-function 'DCSFunction' in
'TimeSteppingRigidBodyManipulator_063597076501216552/DrakeSys':


DrakeSystem S-Function: error MATLAB:innerdim in MATLAB callback.
See additional debugging information above</error_message> 


```

### PR DESCRIPTION
**Pull request by psiorx**
When gurobi is not present, the MATLAB implementation of solveLCP is invoked instead of solveLCPmex.  This implementation bases whether or not contacts should be processed on numContactPairs which is not available in the c++ implementation.

When multiple_contacts are enabled, numContactPairs(determined at compile time) can be incorrect since the actual number of contact pairs is determined by bullet at runtime after performing collision detection. 

Resolves #1035

### CODE REVIEW

File: systems/plants/TimeSteppingRigidBodyManipulator.m [hunk 1]
```diff
@@ -366,58 +366,70 @@ function checkDirty(obj)
...
-            dJ(nL+nP+(1:nC),:) = reshape(dn(possible_contact_indices,:),nC,[]);
-            dD = cellfun(@(A)reshape(A(possible_contact_indices,:),size(D{1},1),size(D{1},2)*size(dD{1},2)),dD,'UniformOutput',false);
-            dD = vertcat(dD{:});
-            dJ(nL+nP+nC+(1:mC*nC),:) = dD;
-          end
-
-          contact_data.normal = normal(:,possible_contact_indices);
-          for i=1:length(d)
-            contact_data.d{i} = d{i}(:,possible_contact_indices);
+          if numel(phiC > 0)
```
Comment (RussTedrake) [inline systems/plants/TimeSteppingRigidBodyManipulator.m]: why is this the right thing to check?  presumably if phiC = 0, then that model has contacts, too?

Comment (psiorx) [inline systems/plants/TimeSteppingRigidBodyManipulator.m]: phiC is the vector of the closest distances between actual contact pairs.  If the vector is empty, there are no contact pairs.  

getNumContactPairs returns a static value based on the number of possible contact pairs but bullet may decide at runtime that none of those pairs are relevant. 

If there are no possible collision pairs, we can skip the call to collisionDetect but collisionDetect should have the ultimate say in whether or not collision pairs should actually be processed.

Comment (RobotLocomotionBuild) [inline systems/plants/TimeSteppingRigidBodyManipulator.m]: ah. that makes sense.  but then you have a typo. sounds like you want `numel(phiC)>0` not  `numel(phiC>0)` ?

is `numel` faster than `isempty`?  (which is what we use almost everywhere else)

Comment (psiorx) [inline systems/plants/TimeSteppingRigidBodyManipulator.m]: Whoops.  Yes, you are correct on both points. Good catch.

**Comment by RussTedrake** [comment]
this one is my fault.  (i'm playing with drake004).  it will error out on a few more tests, too.
