### PR TITLE
Make publish-every-timestep configurable in the Simulator.

### LINKED ISSUE #4359: Mysterious sample times
This is potentially related to #4325 (which was reopened because the sensitivity to floating point errors persists), but i'm opening this issue to address a bigger API question about sample times.

In the unit tests in #4358, I'm registering two systems: a random source which declares a periodic update at 0.0025, an output port with discrete sampling, and a signal logger which declares it's input timing to be "inherited".   If I were to set up the comparable systems in Simulink, I would naively expect the SignalLogger's DoPublish to be called every 0.0025 seconds... but somehow it gets called at times:
```
0
 0.001
 0.002
0.0035
0.0045
 0.006
 0.007
0.0085
0.0095
 0.011
```
Huh!?  I've confirmed that it's using the RungeKutta2Integrator, which should be a fixed-step integrator.  Again, some of the randomness here could be related to the floating point issues, but I think the API is also broken.

I did notice that SamplingSpec in system_port_descriptor.h currently reads
```
/// SamplingSpec describes whether a port has inherited, continuous, or
/// discrete sampling. Since ports in Drake are not actually sampled, this is
/// only potentially useful for detecting unintended connections at Diagram
/// connection time.
// TODO(david-german-tri, sherm1): Consider just getting rid of this.
typedef enum {
  kInherited = 0,
  kContinuous = 1,
  kDiscrete = 2,
} SamplingSpec;
```
That's very misleading!

### PR DESCRIPTION
**Pull request by david-german-tri**
This PR does four closely related things:

1. Adds the ability to configure the Simulator to publish every timestep, or only when the System under simulation requests to publish.

2. When publish-every-timestep is on, fixes a bug so that we actually publish on every timestep, not just the timesteps that end due to hitting the max sample time.

3. Checks whether the System under publish has requested a discrete sample because it wants to publish, do a difference update, or both, and conveys that information to the integrator.

4. Adds support to LeafSystem for configuring both publish and difference-update events at the same time.  (Right now this is only used to test (3), but it is generally useful.)

Fixes #4359 

@edrumwri for feature review, @sherm1  for platform review

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/4372)

### CODE REVIEW

**Comment by sherm1** [comment]
BTW, the reason to distinguish publish times from update times is that publishing can be done with cheap interpolated states while updates must occur between continuous integration intervals. We haven't yet implemented this optimization but I want to make sure the architecture permits it since it can provide a substantial speedup for variable-step integrators.

**Comment by david-german-tri** [comment]
> BTW, the reason to distinguish publish times from update times is that publishing can be done with cheap interpolated states while updates must occur between continuous integration intervals. We haven't yet implemented this optimization but I want to make sure the architecture permits it since it can provide a substantial speedup for variable-step integrators.

Ah, OK, I remember that now.  I'll put it back; the substantive fix in this PR is still the right one.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-:-KYF8M6zzYPQP9FsshWH:b-awkzyr)*

**Comment by david-german-tri** [comment]
> I'll put it back

Done, PTAL

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-:-KYFFpavRksqYORU0pJY:b-52oikr)*

File: drake/systems/analysis/simulator.h [hunk 1]
```diff
@@ -163,6 +163,19 @@ class Simulator {
    */
   double get_actual_realtime_rate() const;
 
+  /** Sets whetheer the simulation should invoke Publish on the System under
```
Comment (Gjacquenot) [inline drake/systems/analysis/simulator.h]: @david-german-tri : There is a typo in the first comment whetheer -> whether

**Comment by david-german-tri** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[drake/systems/analysis/simulator.h, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYF0vrzKuX6ZYmiug43-r1-166:-KYFg6qwh-ShIhNnYTXY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L166)):*
<details><summary><i>Previously, Gjacquenot wrote…</i></summary><blockquote>

@david-german-tri : There is a typo in the first comment whetheer -> whether
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372)*

**Comment by edrumwri** [comment]
Reviewed 4 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFMdxgOmCNhPiE9LXu:-KYFMdxgOmCNhPiE9LXv:b-envhg7) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L166)):*
> ```objc
>   double get_actual_realtime_rate() const;
> 
>   /** Sets whetheer the simulation should invoke Publish on the System under
> ```

I suggest naming this method something else. The method name doesn't specify whether the publishing will happen at the beginning of the step or the end. 

---

*[drake/systems/analysis/simulator.h, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFY251OfX_DYJH_iTm:-KYFY251OfX_DYJH_iTn:b-ycp8nv) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L303)):*
> ```objc
>   double target_realtime_rate_{0.};
> 
>   bool publish_every_timestep_{true};
> ```

I consider "time step" to be two words and would name fields and methods accordingly.

---

*[drake/systems/analysis/simulator.h, line 394 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFW2-08DrdIwHv0h3X:-KYFW2-08DrdIwHv0h3Y:bbxm1s6) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L394)):*
> ```objc
> 
>     // First take any necessary discrete actions.
>     if (sampling_time_hit) {
> ```

Hi David, Sherm and I chose our language precisely here. "Sampling" indicates the process of drawing the next discrete sample "Updating" is a broader term that can involve sampling as well as other events. I personally also found it easier to distinguish what is happening in the code flow by having two separately named variables.

---

*[drake/systems/analysis/simulator.h, line 423 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFXuuz3Lynh3ejzK-r:-KYFXuuz3Lynh3ejzK-s:b-rx3icl) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L423)):*
> ```objc
> 
>     // Allow System a chance to produce some output.
>     if (publish_every_timestep()) {
> ```

The documentation for this method indicates that it will publish at the end of every time step. However, this code will publish at the beginning of the time step (before the integration occurs).

---

*[drake/systems/analysis/test/simulator_test.cc, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFYmnCjsVzKE__PkJq:-KYFYmnDtlDRIstb_Gal:b9yteza) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/test/simulator_test.cc#L196)):*
> ```cpp
> }
> 
> // Tests that if publishing every timestep is disabled, publish only happens
> ```

This test doesn't seem to catch the problem I noted with whether publishing occurs at the beginning or end of the step.

---

*[drake/systems/analysis/test/simulator_test.cc, line 388 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFZ49b_E4KJtFW_iDK:-KYFZ49b_E4KJtFW_iDL:b-uthgft) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/test/simulator_test.cc#L388)):*
> ```cpp
>   void DoPublish(
>       const drake::systems::Context<double>& context) const override {
>     const double k = context.get_time() / 0.0025;
> ```

What is the purpose of these few lines of code? Why the magic numbers (0.0025 and 1e-8)? Why the assertion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372)*

**Comment by david-german-tri** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFMdxgOmCNhPiE9LXu:-KYFmFu6XSlrepNsIdGP:b98m3jv) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L166)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I suggest naming this method something else. The method name doesn't specify whether the publishing will happen at the beginning of the step or the end. 
</blockquote></details>

I've corrected the comment, which I think makes the existing name seem more appropriate.

---

*[drake/systems/analysis/simulator.h, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFY251OfX_DYJH_iTm:-KYFhuhdMP0kAhgSKha7:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L303)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I consider "time step" to be two words and would name fields and methods accordingly.
</blockquote></details>

Done.

---

*[drake/systems/analysis/simulator.h, line 394 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFW2-08DrdIwHv0h3X:-KYFh3qq8WrPxnJi9rf4:b-sjvnlp) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L394)):*
> Hi David, Sherm and I chose our language precisely here. "Sampling" indicates the process of drawing the next discrete sample "Updating" is a broader term that can involve sampling as well as other events. "Sampling" indicates the process of drawing the next discrete sample "Updating" is a broader term that can involve sampling as well as other events.

FWIW, I think it would be worth sacrificing some purity on this point to avoid the current situation, in which "update" and "publish" are both types of "update".  (Pre-existing comments use the word "sampling" to clarify this point, from which I took inspiration!)  But, not worth arguing about, so done.

> I personally also found it easier to distinguish what is happening in the code flow by having two separately named variables.

"update_time_hit" means we hit the time the System under simulation's next discrete event time.  For now, we do exactly the same thing whether it's a publish flavor of update time, or an update flavor of update time, so distinguishing them is confusing IMO.

---

*[drake/systems/analysis/simulator.h, line 423 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFXuuz3Lynh3ejzK-r:-KYFi1Dvi9VL5-s1bXf4:b-ca6elq) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L423)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The documentation for this method indicates that it will publish at the end of every time step. However, this code will publish at the beginning of the time step (before the integration occurs).
</blockquote></details>

Yep, that was an error in the documentation.  I wasn't intending to change the existing behavior.

---

*[drake/systems/analysis/test/simulator_test.cc, line 196 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFYmnCjsVzKE__PkJq:-KYFi6emVUhvgLhcMhDL:bkytmqz) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/test/simulator_test.cc#L196)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This test doesn't seem to catch the problem I noted with whether publishing occurs at the beginning or end of the step.
</blockquote></details>

Done.  (This was tough!)

---

*[drake/systems/analysis/test/simulator_test.cc, line 388 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFZ49b_E4KJtFW_iDK:-KYFhhk3ob49BU7iM7bQ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/test/simulator_test.cc#L388)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

What is the purpose of these few lines of code? Why the magic numbers (0.0025 and 1e-8)? Why the assertion?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372)*

**Comment by edrumwri** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 425 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYG5sNYXOemm1f9g9h6:-KYG5sNYXOemm1f9g9h7:b8hrh6q) ([raw file](https://github.com/robotlocomotion/drake/blob/ceec4c4223b36be4f02edffae1158342dc024d37/drake/systems/analysis/test/simulator_test.cc#L425)):*
> ```cpp
>   const double k = context.get_time() / period;
>   const double int_k = std::round(k);
>   const double kTolerance = 1e-8;
> ```

I expect that this condition will fail to operate as expected if the context time gets to about 10^8.

---

*[drake/systems/analysis/test/simulator_test.cc, line 484 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYG7DBz4-9AoHXPsvOv:-KYG7DBz4-9AoHXPsvOw:b-9fqeo9) ([raw file](https://github.com/robotlocomotion/drake/blob/ceec4c4223b36be4f02edffae1158342dc024d37/drake/systems/analysis/test/simulator_test.cc#L484)):*
> ```cpp
>   simulator.StepTo(0.5);
> 
>   // Check that all the update events precede all the publish events, and all
> ```

Great test!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/systems/analysis/test/simulator_test.cc, line 425 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYG5sNYXOemm1f9g9h6:-KYG8FomAtCWy1VYZU-o:bdsbjl) ([raw file](https://github.com/robotlocomotion/drake/blob/ceec4c4223b36be4f02edffae1158342dc024d37/drake/systems/analysis/test/simulator_test.cc#L425)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I expect that this condition will fail to operate as expected if the context time gets to about 10^8.
</blockquote></details>

That makes sense...but it's not used in any test that does, so I think we're good?

---

*[drake/systems/analysis/test/simulator_test.cc, line 484 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYG7DBz4-9AoHXPsvOv:-KYG8ErT8PkNXZnum7Ec:b-ucfknh) ([raw file](https://github.com/robotlocomotion/drake/blob/ceec4c4223b36be4f02edffae1158342dc024d37/drake/systems/analysis/test/simulator_test.cc#L484)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Great test!
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372)*

**Comment by sherm1** [comment]
Platform review: :lgtm: with a few BTW comments, PTAL.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFMdxgOmCNhPiE9LXu:-KYFrWD_EpJ2L-eT5gN_:bfycajn) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L166)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I suggest naming this method something else. The method name doesn't specify whether the publishing will happen at the beginning of the step or the end. 
</blockquote></details>

BTW, isn't the documentation enough for that? The name seems OK. I do think this method should cause publication at t=0 (more precisely: at start of integration) and the documentation should say so.

---

*[drake/systems/analysis/simulator.h, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFY251OfX_DYJH_iTm:-KYG442xyMSE_EO3k5wZ:b-m9dekr) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L303)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, I'm a one-worder for "timestep" and "realtime" because they are so common in our biz. But I'd be willing to retrain if everyone wants to be all Strunk & White about it.

---

*[drake/systems/analysis/simulator.h, line 394 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFW2-08DrdIwHv0h3X:-KYG5FTQsl2SLD7GFck6:b-x0ngqe) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L394)):*
<details><summary><i>Previously, david-german-tri (David German) wrote…</i></summary><blockquote>

> Hi David, Sherm and I chose our language precisely here. "Sampling" indicates the process of drawing the next discrete sample "Updating" is a broader term that can involve sampling as well as other events. "Sampling" indicates the process of drawing the next discrete sample "Updating" is a broader term that can involve sampling as well as other events.

FWIW, I think it would be worth sacrificing some purity on this point to avoid the current situation, in which "update" and "publish" are both types of "update".  (Pre-existing comments use the word "sampling" to clarify this point, from which I took inspiration!)  But, not worth arguing about, so done.

> I personally also found it easier to distinguish what is happening in the code flow by having two separately named variables.

"update_time_hit" means we hit the time the System under simulation's next discrete event time.  For now, we do exactly the same thing whether it's a publish flavor of update time, or an update flavor of update time, so distinguishing them is confusing IMO.

</blockquote></details>

BTW, "publishing" is not an "update" since it can't cause any state changes. But it shares the same event-triggering conditions with actual updates, and reaching a sample time is one of those triggers. So I like the `sample_time_hit` name here.

---

*[drake/systems/analysis/simulator.h, line 177 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFybCgoOQm8eYVJXKh:-KYFybCgoOQm8eYVJXKi:b-jaq1b6) ([raw file](https://github.com/robotlocomotion/drake/blob/2e12aa288bdcae4acfc85a5bd8025a6534d512b5/drake/systems/analysis/simulator.h#L177)):*
> ```objc
>    */
>   // TODO(sherm1, edrumwri): Consider making this false by default.
>   bool publish_every_timestep() const { return publish_every_timestep_; }
> ```

BTW, consider an initial "boolean" verb like `should_publish_every_timestep()` or just `get_publish_every_timestep()` to make it clear that this is just returning a flag (otherwise "publish" seems like the verb but this method doesn't publish anything).

---

*[drake/systems/analysis/simulator.h, line 438 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYG6YmnRzYSg8LoxKBy:-KYG6YmoyPubGrLZbJku:b-56vxu7) ([raw file](https://github.com/robotlocomotion/drake/blob/2e12aa288bdcae4acfc85a5bd8025a6534d512b5/drake/systems/analysis/simulator.h#L438)):*
> ```objc
>     T next_update_dt = std::numeric_limits<double>::infinity();
>     T next_publish_dt = std::numeric_limits<double>::infinity();
>     for (const DiscreteEvent<T>& event : update_actions.events) {
> ```

BTW, I was confused reading this code. The loop made me think that it was searching for the earliest event. After talking with @edrumwri I understand that the update_actions come from CalcNextUpdateTime() which I believe is required already to have reported just the earliest times. So if there are multiple publish events they should be simultaneous and similarly for multiple update events. (a) is that right?, and (b) if so I think a comment here would be very helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-:-KYG8jX-d8Rnk0r-xmLz:b-lx5vp3)*

**Comment by david-german-tri** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/systems/analysis/simulator.h, line 166 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFMdxgOmCNhPiE9LXu:-KYGCP0yZ7S9Xr5W2t_1:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L166)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, isn't the documentation enough for that? The name seems OK. I do think this method should cause publication at t=0 (more precisely: at start of integration) and the documentation should say so.
</blockquote></details>

Done.

---

*[drake/systems/analysis/simulator.h, line 303 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFY251OfX_DYJH_iTm:-KYGCRpiTYmz9YmcOUw4:b-lujxuk) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L303)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I'm a one-worder for "timestep" and "realtime" because they are so common in our biz. But I'd be willing to retrain if everyone wants to be all Strunk & White about it.
</blockquote></details>

I agree with Sherm but don't care enough to find and replace again until everyone else has achieved consensus.

---

*[drake/systems/analysis/simulator.h, line 394 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFW2-08DrdIwHv0h3X:-KYGCitXnr0HDc2Z27Ci:b-p2llau) ([raw file](https://github.com/robotlocomotion/drake/blob/3ea68fc1f439d5ebea7bfca7b6fa1a9f539f3ae1/drake/systems/analysis/simulator.h#L394)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, "publishing" is not an "update" since it can't cause any state changes. But it shares the same event-triggering conditions with actual updates, and reaching a sample time is one of those triggers. So I like the `sample_time_hit` name here.
</blockquote></details>

Splendid!  This one I do care enough to find-and-replace, now that Evan is outvoted.

---

*[drake/systems/analysis/simulator.h, line 177 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYFybCgoOQm8eYVJXKh:-KYGCaIv0UtKG1eVgkYT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake/blob/2e12aa288bdcae4acfc85a5bd8025a6534d512b5/drake/systems/analysis/simulator.h#L177)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, consider an initial "boolean" verb like `should_publish_every_timestep()` or just `get_publish_every_timestep()` to make it clear that this is just returning a flag (otherwise "publish" seems like the verb but this method doesn't publish anything).
</blockquote></details>

Done.

---

*[drake/systems/analysis/simulator.h, line 438 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-KYG6YmnRzYSg8LoxKBy:-KYGCvbkhyn_z3JJxthr:bluznx7) ([raw file](https://github.com/robotlocomotion/drake/blob/2e12aa288bdcae4acfc85a5bd8025a6534d512b5/drake/systems/analysis/simulator.h#L438)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW, I was confused reading this code. The loop made me think that it was searching for the earliest event. After talking with @edrumwri I understand that the update_actions come from CalcNextUpdateTime() which I believe is required already to have reported just the earliest times. So if there are multiple publish events they should be simultaneous and similarly for multiple update events. (a) is that right?, and (b) if so I think a comment here would be very helpful.
</blockquote></details>

That's correct.  Comment added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372)*

**Comment by edrumwri** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake/4372#-:-KYGDkXFdeK-RFX2WsSy:bnfp4nl)*
