### PR TITLE
resolves segfault on windows in compareParsers 

### LINKED ISSUE #1037: ﻿segfault on windows in compareParsers
Site: DRAKE003
Build Name: precompiled-pull-rdeits-rd-fix-double-plan-shift-into-RobotLocomotion-master
Build Server Directory: C:/cygwin64/tmp/drake-precompiled/drake-18181
Pull Request: #1032
CDash: http://kobol.csail.mit.edu/cd/viewTest.php?onlyfailed&buildid=12707

Most recent commits to drake included in this build:

ab6de14 Merge branch 'rd-fix-double-plan-shift' of https://github.com/rdeits/drake
c927a7a Merge pull request #1031 from hongkai-dai/fix-testDrakeGeometryUtil
662324c don't apply plan shift twice to toe-off foot
26b940a add support for only applying plan shift to ZMP xy pose
1747970 zap error msg in testDrakeGeometryUtil

```
C:/Program Files/MATLAB/R2012a/bin/win64/MATLAB.exe
 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
To reproduce this test use rng(1008668986,'twister')
 
{ Warning: Disabling autosave for simulink blocks (to avoid generating a lot of *.mdl.autosave files in your
directory.  If you aren't a regular Simulink user and don't want this disabled, comment out this section
in addpath_drake.
To disable this warning in the future, add
   warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m}  
{ > In addpath_drake at 74
  In addpath_drake at 4}  
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Acrobot\Acrobot.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Acrobot\test\AcrobotWParams.urdf
 Calling addpath_spotless
 this model has parameters (not implemented in c++ yet), so will be skipped
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\atlas_convex_hull.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\atlas_minimal_contact.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\block_hand.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\door.urdf
 this model had force elements (not implemented in c++ yet)
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\drill_frame.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\robotiq.urdf
{ Warning: 3D loop joints do not properly enforce the joint axis constraint.  (they perform more like a ball
joint)}  
{ > In WarningManager>WarningManager.warnOnce at 21
  In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
  In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
  In RigidBodyManipulator.addRobotFromURDF at 54
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 72
  In compareParsers at 22
  In fevalPackageSafe at 21}  
{ Warning: still need to add time derivatives of position constraints}  
{ > In WarningManager>WarningManager.warnOnce at 21
  In Manipulator.Manipulator>Manipulator.updatePositionEqualityConstraint at 192
  In Manipulator.Manipulator>Manipulator.addPositionEqualityConstraint at 169
  In RigidBodyLoop>RigidBodyLoop.updateConstraints at 27
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at 856
  In RigidBodyManipulator.addRobotFromURDF at 59
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 72
  In compareParsers at 22
  In fevalPackageSafe at 21}  
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\robotiq_box.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\robotiq_simple.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\robotiq_tendons.urdf
{ Warning: still need to add time derivatives of position constraints}  
{ > In WarningManager>WarningManager.warnOnce at 21
  In Manipulator.Manipulator>Manipulator.updatePositionEqualityConstraint at 192
  In Manipulator.Manipulator>Manipulator.addPositionEqualityConstraint at 169
  In RigidBodyManipulator.addRobotFromURDF>parseCable at 532
  In RigidBodyManipulator.addRobotFromURDF>parseRobot at 135
  In RigidBodyManipulator.addRobotFromURDF at 54
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 72
  In compareParsers at 22
  In fevalPackageSafe at 21}  
 this model has parameters (not implemented in c++ yet), so will be skipped
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Atlas\urdf\valve_wall.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\FurutaPendulum\FurutaPendulum.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\Glider\GliderBalanced.urdf
Constructing a new airfoil
Using a flat plate airfoil.
Constructing a new airfoil
Using a flat plate airfoil.
 this model had force elements (not implemented in c++ yet)
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\IRB140\urdf\ATI_sensor.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\IRB140\urdf\irb_140.urdf
testing C:\cygwin64\tmp\drake-precompiled\drake-18181\examples\IRB140\urdf\irb_140_robotiq.urdf
{ Warning: 3D loop joints do not properly enforce the joint axis constraint.  (they perform more like a ball
joint)}  
{ > In WarningManager>WarningManager.warnOnce at 21
  In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
  In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
  In RigidBodyManipulator.addRobotFromURDF at 54
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 72
  In compareParsers at 22
  In fevalPackageSafe at 21}  
{ Warning: still need to add time derivatives of position constraints}  
{ > In WarningManager>WarningManager.warnOnce at 21
  In Manipulator.Manipulator>Manipulator.updatePositionEqualityConstraint at 192
  In Manipulator.Manipulator>Manipulator.addPositionEqualityConstraint at 169
  In RigidBodyLoop>RigidBodyLoop.updateConstraints at 27
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at 856
  In RigidBodyManipulator.addRobotFromURDF at 59
  In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 72
  In compareParsers at 22
  In fevalPackageSafe at 21}  
```

﻿```
------------------------------------------------------------------------
       Segmentation violation detected at Thu Apr 23 13:08:32 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding  : Disabled
  Default Encoding: windows-1252
  MATLAB Root     : C:\Program Files\MATLAB\R2012a
  MATLAB Version  : 7.14.0.739 (R2012a)
  Operating System: Microsoft Windows 7
  Processor ID    : x86 Family 6 Model 23 Stepping 6, GenuineIntel
  Virtual Machine : Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System   : Version 6.2 (Build 9200)

Fault Count: 1

Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 00000000152165b0
  RCX = 0000000004fe6610  RDX = 00000000152167e0
  RSP = 0000000004fe65f0  RBP = 00000000152167e0
  RSI = 00000000167eeff0  RDI = 00000000167ef000

   R8 = 0000000000000000   R9 = 00000000000000f0
  R10 = 0000000000000000  R11 = 0000000000000022
  R12 = 0000000000000000  R13 = 00000000169502c0
  R14 = 0000000000000080  R15 = 0000000000000008

  RIP = 00007ffe9559dd75  EFL = 00010283

   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x00007ffe9559dd75 C:\cygwin64\tmp\drake-precompiled\drake-18181\pod-build\lib\Release\drakeRBM.dll+00056693 ( RigidBodyActuator::Rig
idBodyActuator+004645 )
[  1] 0x00007ffe955c2aec C:\cygwin64\tmp\drake-precompiled\drake-18181\pod-build\lib\Release\drakeRBM.dll+00207596 ( RigidBodyManipulator::
compile+000396 )
[  2] 0x00007ffe9560fefc C:\cygwin64\tmp\drake-precompiled\drake-18181\pod-build\lib\Release\drakeRBM.dll+00524028 ( RigidBodyManipulator::
operator=+035228 )
[  3] 0x00007ffe956101b7 C:\cygwin64\tmp\drake-precompiled\drake-18181\pod-build\lib\Release\drakeRBM.dll+00524727 ( RigidBodyManipulator::
addRobotFromURDF+000423 )
[  4] 0x00007ffe956103c9 C:\cygwin64\tmp\drake-precompiled\drake-18181\pod-build\lib\Release\drakeRBM.dll+00525257 ( RigidBodyManipulator::
addRobotFromURDF+000121 )
[  5] 0x00007ffe955c96b9 C:\cygwin64\tmp\drake-precompiled\drake-18181\pod-build\lib\Release\drakeRBM.dll+00235193 ( RigidBodyManipulator::
RigidBodyManipulator+000873 )
[  6] 0x00007ffe957c92f7 C:\cygwin64\tmp\drake-precompiled\drake-18181\systems\plants\test\compareParsersmex.mexw64+00037623 ( mexFunction+
000455 )
[  7] 0x000000005d0f0f63 C:\Program Files\MATLAB\R2012a\bin\win64\libmex.dll+00069475 ( mexRunMexFile+000131 )
[  8] 0x000000005d0efce2 C:\Program Files\MATLAB\R2012a\bin\win64\libmex.dll+00064738 ( inSwapMexfileReader+000226 )
[  9] 0x000000005d0efe58 C:\Program Files\MATLAB\R2012a\bin\win64\libmex.dll+00065112 ( inSwapMexfileReader+000600 )
[ 10] 0x000000005d02b046 C:\Program Files\MATLAB\R2012a\bin\win64\m_dispatcher.dll+00045126 ( Mfh_file::dispatch_fh+000486 )
[ 11] 0x000000005d02b93c C:\Program Files\MATLAB\R2012a\bin\win64\m_dispatcher.dll+00047420 ( Mfunction_handle::dispatch+000812 )
[ 12] 0x000000005b9d4ff3 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00479219 ( inDestroyWS+193347 )
[ 13] 0x000000005b9d6668 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00484968 ( inDestroyWS+199096 )
[ 14] 0x000000005b9be41f C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00386079 ( inDestroyWS+100207 )
[ 15] 0x000000005b9be390 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00385936 ( inDestroyWS+100064 )
[ 16] 0x000000005b9d1ae1 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00465633 ( inDestroyWS+179761 )
[ 17] 0x000000005b9d2cca C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00470218 ( inDestroyWS+184346 )
[ 18] 0x000000005b9c5709 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00415497 ( inDestroyWS+129625 )
[ 19] 0x000000005d02b046 C:\Program Files\MATLAB\R2012a\bin\win64\m_dispatcher.dll+00045126 ( Mfh_file::dispatch_fh+000486 )
[ 20] 0x000000005d02b93c C:\Program Files\MATLAB\R2012a\bin\win64\m_dispatcher.dll+00047420 ( Mfunction_handle::dispatch+000812 )
[ 21] 0x000000005b9d4ff3 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00479219 ( inDestroyWS+193347 )
[ 22] 0x000000005ba5f373 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+01045363 ( inEachVisibleName+020035 )
[ 23] 0x000000005b9d7f37 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00491319 ( inDestroyWS+205447 )
[ 24] 0x000000005b9be41f C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00386079 ( inDestroyWS+100207 )
[ 25] 0x000000005b9be390 C:\Program Files\MATLAB\R2012a\bin\win64\m_interpreter.dll+00385936 ( inDestroyWS+100064 )
...
```

### PR DESCRIPTION
**Pull request by RussTedrake**
but could have been impacting other processes as well.  this one was on me.

resolves #1037.

### CODE REVIEW

File: systems/plants/RigidBodyManipulator.cpp [hunk 1]
```diff
@@ -363,12 +363,12 @@ void RigidBodyManipulator::compile(void)
 {
   // reorder body list to make sure that parents before children in the list
 	size_t i=0;
-  while (i<bodies.size()) {
+  while (i<bodies.size()-1) {
```
Comment (hongkai-dai) [inline systems/plants/RigidBodyManipulator.cpp]: In #1054 we changed some `size_t` to `int`, should we also do it herein line 365?

Comment (RussTedrake) [inline systems/plants/RigidBodyManipulator.cpp]: size_t is the right thing if you are comparing to the size of a vector, etc.  
the change in #1054 was because size_t was used for the body_index, which is a good old-fashioned int.

**Comment by avalenzu** [comment]
+1
