### PR TITLE
Polynomial updates

### LINKED ISSUE #1008: Polynomial class addition doesn't produce the correct result for polynomials of different degree
I tried a simple polynomial addition test, adding a degree 5 and a degree 2 polynomial together. The result is incorrect for the final coefficient: 

```
my coefs:      1.2
     0.3
    0.09
   0.018
  0.0027
0.000324
my coefs resized:      1.2
     0.3
    0.09
   0.018
  0.0027
0.000324
other coefs: -0.09375
   -0.25
    -2.5
my coefs after: 1.10625
   0.05
  -2.41
  0.018
 0.0027
1.00032
```

Note that the last term should be 0.00032, not 1.00032. Here are the print statements I added:

```
Polynomial& Polynomial::operator+=(const Polynomial& other) {
  std::cout << "my coefs: " << coefficients << std::endl;
  int old_num_coefficients = getNumberOfCoefficients();
  int new_num_coefficients = max(old_num_coefficients, other.getNumberOfCoefficients());
  coefficients.conservativeResize(new_num_coefficients);
  coefficients.segment(old_num_coefficients, new_num_coefficients - old_num_coefficients).setZero();
  std::cout << "my coefs resized: " << coefficients << std::endl;
  std::cout << "other coefs: " << other.coefficients << std::endl;
  coefficients += other.coefficients;
  std::cout << "my coefs after: " << coefficients << std::endl;
  return *this;
}
```

It looks like the problem is that there's no resizing of other.coefficients if it happens to be smaller than this.coefficients.

### PR DESCRIPTION
**Pull request by tkoolen**
* fix addition (fixes #1008)
* add a bunch more operators (feature request from @rdeits)
* add roots function (uses Eigen's root solver). Definitely good enough for now, but see comments below
* add a templated valuecheck that just uses !=
* templatize Polynomial and PiecewisePolynomial so that they (and code using them) are future proof - I want these classes to be able to handle symbolic scalar types, AutoDiffScalar, complex coefficients, ... sometime in the future.

About Eigen's PolynomialSolver: here's what they say about it:
```
 /*
  * WARNING: this polynomial solver is experimental, part of the unsuported Eigen modules.
  *
  *
  * Currently a QR algorithm is used to compute the eigenvalues of the companion matrix of
  * the polynomial to compute its roots.
  * This supposes that the complex moduli of the roots are all distinct: e.g. there should
  * be no multiple roots or conjugate roots for instance.
  * With 32bit (float) floating types this problem shows up frequently.
  * However, almost always, correct accuracy is reached even in these cases for 64bit
  * (double) floating types and small polynomial degree (<20).
  /*
```
This comment may be outdated. This description makes it seem like it can't compute complex roots at all, but it definitely can.
It's able to handle different real scalar types for the coefficients, but it can't handle polynomials with complex coefficients, so we'd need to implement that ourselves if we need it.

### CODE REVIEW

File: util/test/testUtil.h [hunk 1]
```diff
@@ -50,4 +50,14 @@ void valuecheck(double a, double b, double tolerance = 1e-8)
   }
 }
 
+template <typename T>
+void valuecheck(T const & a, T const & b)
```
Comment (RussTedrake) [inline util/test/testUtil.h]: this is just exacerbating the problem.  instead of adding this, can you just make the change to using the drakeUtil.h valuecheck (moving it to testUtil.h is aok with me)?

**Comment by RussTedrake** [comment]
it's a lot of changes, so hard for me to check carefully.  but looks good.  nice to think we might use the complex version eventually.

**Comment by RussTedrake** [comment]
code looks good.  thx.  just waiting on windows build servers. (they're working on it!)

**Comment by tkoolen** [comment]
Rebased and fixed valuecheck call.
