### PR TITLE
Fixed forwardKin wraparound errors

### LINKED ISSUE #774: testForwardKin fails with wrap-around errors
using the new kinsol, we sometimes get errors that are simply off by 2*pi.

systems/plants/test/testForwardKin (unknown issue)
```
error_id = Drake:ValueCheck
error_message = Values don't match.  Expected 
[1.39706212691382 0.982932283798885 -0.179440634922389 0.400673174035788 0.000307679966546903;0.0659853492088657 0.415979545234059 1.43816405956632 0.984881801517688 -1.32229448619544;-0.925506492945206 0.897273646432425 1.06739875173278 -1.18220109265525 -0.880989570227474;2.18256881272747 2.18256881272747 2.18256881272747 2.18256881272747 2.18256881272747;-0.680624221941156 -0.680624221941156 -0.680624221941156 -0.680624221941156 -0.680624221941156;3.14159265358979 3.14159265358979 3.14159265358979 3.14159265358979 3.14159265358979]
 but got 
[1.39706212691382 0.982932283798885 -0.179440634922389 0.400673174035788 0.000307679966546792;0.0659853492088658 0.415979545234059 1.43816405956632 0.984881801517686 -1.32229448619543;-0.925506492945205 0.897273646432425 1.06739875173278 -1.18220109265525 -0.880989570227473;2.18256881272747 2.18256881272747 2.18256881272747 2.18256881272747 2.18256881272747;-0.680624221941156 -0.680624221941156 -0.680624221941156 -0.680624221941156 -0.680624221941156;-3.14159265358979 -3.14159265358979 -3.14159265358979 -3.14159265358979 -3.14159265358979]
is_segfault = 0
```
```Matlab

                            < M A T L A B (R) >
                  Copyright 1984-2012 The MathWorks, Inc.
                    R2012b (8.0.0.783) 64-bit (glnxa64)
                              August 22, 2012

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
To reproduce this test use rng(442483817,'twister')
 
[Warning: Disabling autosave for simulink blocks (to avoid generating a lot of
*.mdl.autosave files in your directory.  If you aren't a regular Simulink user
and don't want this disabled, comment out this section in addpath_drake.
To disable this warning in the future, add
   warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m] 
[> In addpath_drake at 74
  In addpath_drake at 4] 
Error using valuecheck (line 78)
Values don't match.  Expected 
[1.39706212691382 0.982932283798885 -0.179440634922389 0.400673174035788 0.000307679966546903;0.0659853492088657 0.415979545234059 1.43816405956632 0.984881801517688 -1.32229448619544;-0.925506492945206 0.897273646432425 1.06739875173278 -1.18220109265525 -0.880989570227474;2.18256881272747 2.18256881272747 2.18256881272747 2.18256881272747 2.18256881272747;-0.680624221941156 -0.680624221941156 -0.680624221941156 -0.680624221941156 -0.680624221941156;3.14159265358979 3.14159265358979 3.14159265358979 3.14159265358979 3.14159265358979]
 but got 
[1.39706212691382 0.982932283798885 -0.17944063

**This post was going to be too long and has been truncated**
```
I think it's fine to just make these unit tests more robust.  It seems to only happen at exactly pi and -pi.

<matlab_test>strcmp(test_name,'systems/plants/test/testForwardKin') && ~isempty(strfind(test_output,'3.1415'))</matlab_test>

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes #774.

Also handling the check with a quaternion rotation type differently. Let me know if you think this is a bad idea.

### CODE REVIEW

File: util/rotationRepresentationSize.m [hunk 1]
```diff
@@ -0,0 +1,15 @@
+function ret = rotationRepresentationSize(rotation_type)
```
Comment (RussTedrake) [inline util/rotationRepresentationSize.m]: the notation of the rotation_type only makes sense in the context of our RBM classes.  so I think this should as a static method of RBM, not in the util folder

**Comment by RussTedrake** [comment]
i think it's a reasonable thing to do.  just had one minor comment.
btw - github is having serious issues today, so the build servers are failing on a number of checkouts.

**Comment by tkoolen** [comment]
rotation_type is already used in angularvel2RepresentationDotMatrix.m and rotmat2Representation.m in util. The C++ code for these also lives in util. I think it's fine, but if you really want to move it I will.
