### PR TITLE
BUG_FIX: Implements fixes on the collision coordinate transformation used to compute collision forces

### LINKED ISSUE #1940: Improve on the accuracy of the contact and collision engine
I've been working with height maps in #1616 and in my last test that you can see [here](https://www.youtube.com/watch?v=BOGBV8s14GQ) I get very unphysical results when a ball collides with a height map in an angle. 

I therefore made a simpler test of a ball bouncing on an inclined plane at 45 degrees. An analytical solution is available in this case. No friction, no damping. Second order RK. No multi-contact. You can see an animation [here](https://www.youtube.com/watch?v=2T47WVrhBFk).

inclined_plane_vs_ball

As you can see the physics is also wrong in this simple example with convex objects (using Drake's original implementation).

### PR DESCRIPTION
**Pull request by amcastro-tri**
This fixes #1940. 

The fix is within RigidBodySystem::dynamics where the transformation `R` that transforms from the world frame into the collision point frame was incorrectly computed:

1. The transformation `R` was not a rotation but a rotation plus a reflection. The problem was on the computation of tangent2 which resulted on a frame which was not right handed.
2. The transformation matrix `R` that transforms from the world frame to the collision point frame was implemented as the transpose of what it actually should be. Therefore the inverse of the transformation was implemented instead.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
How about adding a unit test?

**Comment by amcastro-tri** [comment]
@jwnimmer-tri. #1944 implements a test for fix. However since the fix is pretty isolated I decided to push it separately. The test is already implemented in #1944 once it's approved. I'll post a video with results next.

**Comment by amcastro-tri** [comment]
A demonstration of the correct behavior of the test implemented in #1944 can be seen in [this video](https://www.youtube.com/watch?v=j5a46_rkka4).

Results obtained with the original implementation can be seen in [this other video](https://www.youtube.com/watch?v=2T47WVrhBFk). 

@sherm1, your intuition was right! one of the transformations was wrong (actually it was the inverse).

File: drake/systems/plants/RigidBodySystem.cpp [hunk 1]
```diff
@@ -134,9 +134,11 @@ RigidBodySystem::StateVector<double> RigidBodySystem::dynamics(
           tangent1 /= sqrt(this_normal(1) * this_normal(1) +
                            this_normal(0) * this_normal(0));
         }
-        Vector3d tangent2 = tangent1.cross(this_normal);
+        Vector3d tangent2 = this_normal.cross(tangent1);
```
Comment (sherm1) [inline drake/systems/plants/RigidBodySystem.cpp]: This is right now because a right handed frame x,y,z should have the circular property x=yXz, y=zXx, z=xXy. The bug was an example of a notational error IMO because "tangent1" and "tangent2" are insufficient to convey handedness. But ... creating a frame given one of its axes is such a common operation that it ought to be done in a utility method so it only has to be done once! I'm not sure if Eigen has that operation, but it does have one for creating a [unit orthogonal vector](http://eigen.tuxfamily.org/dox/classEigen_1_1MatrixBase.html#a42fdca0c5854b85d9482853c8a085dc1) to a given vector.

File: drake/systems/plants/RigidBodySystem.cpp [hunk 2]
```diff
@@ -134,9 +134,11 @@ RigidBodySystem::StateVector<double> RigidBodySystem::dynamics(
...
         Matrix3d R;  // rotation into normal coordinates
-        R << tangent1, tangent2, this_normal;
+	R.row(0) = tangent1;
+	R.row(1) = tangent2;
+	R.row(2) = this_normal;
         auto J = R * (JA - JB);          // J = [ D1; D2; n ]
```
Comment (sherm1) [inline drake/systems/plants/RigidBodySystem.cpp]: In the absence of bulletproof notation, this kind of code needs careful commenting. I'd start by making sure every frame has a name. In this case, we're building a contact frame C, with Cx=tangent1, Cy=tangent2, Cz=this_normal. We have Jacobians JA and JB that map from joint space velocity to velocities in world (Cartesian) space W (not sure if that's what it's called in Drake). We're going to need a rotation matrix that maps from W to C. In Kane's notation when typeset, that would look like
```
 C   C W    W
v  =  R  * v
```
meaning that the vector on the right is expressed in W and re-expressed in C which can be seen by inspection of the superscripts, in which adjacent ones must always match. In code this can be flattened using "monogram" notation in which the important thing comes first and then the frame follow in order: `v_C = R_CW * v_W`, for example. Now a rotation matrix `R_AB` is constructed by expressing B's axes in A, and then arranging them in columns. In the code above the axes of C are expressed in W, so we have R_WC=[Cx Cy Cz]. By filling this in row-wise as you did above you constructed the transpose R_CW=R_WC' (Matlab notation).

My point is that the code is doing a lot of simple transformations and if each one is clearly documented (ideally with a good notation) then the whole thing has to work. Without that it usually comes down to trial and error!

**Comment by sherm1** [comment]
Nice fix, Alejandro. The code looks good to me but IMO it was broken previously because it was poorly documented (and used essentially random notation). Since you had to think about it carefully to fix it, I would like to see your clear thoughts preserved in some comments there. Otherwise it is ready to merge.

**Comment by amcastro-tri** [comment]
Thank you so much for the review @sherm1! What I'll do is to add documentation as you suggested. Also I would like to try your notation in code. I agree in that we need a standard notation. 
Lets see if I get it right. In my notes I was denoting the minimal coordinates space with q, the world space with w and, as in the code, indexes A and B for the bodies
R -->R_cw
JA-->JA_qw
JB-->JB_qw
this_normal-->Cz_w
tangent1-->Cx_w
tangent2-->Cy_w
v-->qdot
relative_velocity-->relative_velocity_c
fA-->fA_c

**Comment by amcastro-tri** [comment]
Also thanks @jwnimmer-tri. Based on your suggestion I already started today to work on making #1944 a  unit test with analytical solution. I'll submit it in a separate PR.

File: drake/systems/plants/RigidBodySystem.cpp (hunk 2 above)
Comment (liangfok) [inline drake/systems/plants/RigidBodySystem.cpp]: In addition to adopting a bullet proof notation, I'm very curious whether we can exploit the object-oriented nature of C++ to programmatically prevent frame transformation errors.

**Comment by sherm1** [comment]
> Lets see if I get it right. In my notes I was denoting the minimal coordinates space with q, the world space with w and, as in the code, indexes A and B for the bodies

Well, there are a few rough spots. This will be much easier to discuss in person so I'll just say what they are without elaborating.
- q is the generalized coordinate space; that is actually *not* joint space
- v is the generalized speed space; that actually *is* joint space
- qdot != v, in general. They are related like this: qdot = N(q)*v, where N is block diagonal.
- Frames should always be written with a capital letter, and rigid bodies are a kind of frame
- The "A" and "B" are here to represent points (JA, e.g. is the Jacobian of a particular point fixed to body A)
- I don't try to encode the generalized coord/speed spaces in symbols; they aren't frames

Takes a little practice! :smile:

File: drake/systems/plants/RigidBodySystem.cpp (hunk 2 above)
Comment (sherm1) [inline drake/systems/plants/RigidBodySystem.cpp]: > I'm very curious whether we can exploit the object-oriented nature of C++ to programmatically prevent frame transformation errors.

I have seen that done ([MotionGenesis](http://www.motiongenesis.com/MGWebSite/MGSoftwareFeatures/MGSoftwareFeaturePhysics.html) for example) but per Alejandro's concern it comes at a steep cost if used in the guts of a numerical dynamics code. MG can afford it because it is a symbolic code -- once it is done it generates source code that contains none of that stuff.

Reasonable notation and some discipline works too and can be implemented at zero cost. Also I'm not convinced that smarter objects actually prevent all the errors you would want them to -- there is still room for the weak link at the keyboard to make frame errors even if the objects themselves refuse to do so.

**Comment by RussTedrake** [comment]
agreed.  i don't like the notation as suggested, but do love the idea of cleaning it up. am in favor variable names that are readable by a non-expert.  And details like qdot != v are super important to get right.

**Comment by amcastro-tri** [comment]
@sherm1, I guess I still don't understand what `v` is then. Is there any good reference you would recommend for me to read on this regard?

**Comment by sherm1** [comment]
> @amcastro-tri: I guess I still don't understand what v is then. Is there any good reference you would recommend for me to read on this regard?

Did this get cleared up in the meeting this morning? Generalized coordinates q can be chosen somewhat arbitrarily for convenience (Euler angles) or good numerical behavior (quaternions); generalized velocities v are tied closely to the physics (e.g. the number of v's associated with a joint must match the number of dofs provided by that joint). A ball (spherical) joint typically has 4 q's (a quaternion) but 3 v's (an angular velocity vector). Hence qdot can't be v, but they are linearly related.

[This paper](https://simtk.org/docman/view.php/47/1536/Seth-2010-ShermanEastmanDelp-MinimalJointFormulationForBiomechanisms-NonlinearDyn-v62-p291.pdf) might be helpful, or could be overkill for what you want to know. (What it calls "u" is what Drake calls "v".)

**Comment by amcastro-tri** [comment]
@sherm1, yes, the discussion in our meeting was very helpful. Thank you for the reference!

**Comment by amcastro-tri** [comment]
@sherm1, if you agree I'll ask @RussTedrake to merge this PR. Once we decide on a common notation I will go ahead and create a separate PR with a cleaner notation. I will go ahead now and create a separate issue on this.

**Comment by sherm1** [comment]
> if you agree I'll ask @RussTedrake to merge this PR. Once we decide on a common notation I will go ahead and create a separate PR with a cleaner notation.

:+1: I agree this isn't the place to deal with notation. Let's discuss this week when I'm there.

**Comment by RussTedrake** [comment]
@jamiesnape -- why did the win64 report failure?
