### PR TITLE
Fix function names in OptimizationProblem (and related)

### LINKED ISSUE #1984: OptimizationProblem function names don't match style guide
As mentioned in #1962, this class needs cleaned up to match the style guide (particularly around function names).

Creating a ticket to that effect.

### PR DESCRIPTION
**Pull request by sammy-tri**
Rename many functions/variables from the drake/solvers directory to be more compatible with the style guide.

This originally came up in #1962, and was moved into a separate PR.  Fixes #1984.

### CODE REVIEW

File: drake/solvers/MathematicalProgram.cpp [hunk 1]
```diff
@@ -106,9 +115,11 @@ class NonlinearProgram : public MathematicalProgram {
     MixedIntegerQuadraticProgram {};
     struct LinearProgram : public QuadraticProgram, public
     MixedIntegerLinearProgram {
-    virtual MathematicalProgramInterface* addLinearEqualityConstraint() { return new
+    virtual MathematicalProgramInterface* AddLinearEqualityConstraint() { return
+   new
     LinearProgram; };
-    virtual MathematicalProgramInterface* addLinearInequalityConstraint() { return
+    virtual MathematicalProgramInterface* AddLinearInequalityConstraint() {
+   return
```
Comment (ggould-tri) [inline drake/solvers/MathematicalProgram.cpp]: This syntax (return on a separate line from new) is somewhat curious.

**Comment by ggould-tri** [comment]
Apart from the nit noted above, r=ggould.  However I have not comprehensively checked if the matlab and/or snopt excitement experienced by #1921 applies here; CI will presumably tell you if so.

**Comment by sammy-tri** [comment]
It passed once: https://drake-jenkins.csail.mit.edu/job/experimental/671/  -- I'm cautiously optimistic.

**Comment by jwnimmer-tri** [comment]
@sammy-tri Convince me that either your machine, or some CI, has compiled this in Debug mode, so that expressions in `assert()` are actually syntax-checked.

**Comment by sammy-tri** [comment]
41/42 tests have passed on my machine.  I'm still waiting for the debug run of testDrakeGeometryUtil to complete, and I think I might be waiting for a while.  I kinda doubt that this change broke it.

I'd only been running testOptimizationProblem for debug builds prior to your suggestion, agreed that wider scope should have been tested.

File: drake/solvers/MathematicalProgram.cpp [hunk 2]
```diff
@@ -106,9 +115,10 @@ class NonlinearProgram : public MathematicalProgram {
     MixedIntegerQuadraticProgram {};
     struct LinearProgram : public QuadraticProgram, public
     MixedIntegerLinearProgram {
-    virtual MathematicalProgramInterface* addLinearEqualityConstraint() { return new
+    virtual MathematicalProgramInterface* AddLinearEqualityConstraint() { return
+   new
     LinearProgram; };
```
Comment (jwnimmer-tri) [inline drake/solvers/MathematicalProgram.cpp]: Is this actually want clang-format does?  Ick.
Is it worth trying to `// BR` on prior lines here to choose where wrapping happens?

File: drake/solvers/MathematicalProgram.cpp [hunk 3]
```diff
@@ -119,70 +129,68 @@ class NonlinearProgram : public MathematicalProgram {
...
-  addLinearComplementarityConstraint() override {
+  virtual MathematicalProgramInterface* AddLinearComplementarityConstraint()
+      override {
     return new LinearComplementarityProblem;
   };
 };
 
-class LeastSquares
-    : public NonlinearProgram {  // public LinearProgram, public
+class LeastSquares : public NonlinearProgram {  // public LinearProgram, public
```
Comment (jwnimmer-tri) [inline drake/solvers/MathematicalProgram.cpp]: This comment is stupid, but I guess not your fault.
I will live with leaving it alone, and accept this montonically-better patch as-is.

File: drake/solvers/MathematicalProgram.cpp [hunk 4]
```diff
@@ -119,70 +129,68 @@ class NonlinearProgram : public MathematicalProgram {
...
-      for (const DecisionVariableView& v : binding.getVariableList()) {
+      for (const DecisionVariableView& v : binding.variable_list()) {
         Aeq.block(constraint_index, v.index(), n, v.size()) =
-            c->getMatrix().middleCols(var_index, v.size());
+            c->A().middleCols(var_index, v.size());
         var_index += v.size();
       }
       beq.segment(constraint_index, n) =
-          c->getLowerBound();  // = c->getUpperBound() since it's an equality
+          c->lower_bound();  // = c->getUpperBound() since it's an equality
```
Comment (jwnimmer-tri) [inline drake/solvers/MathematicalProgram.cpp]: The function name in the comment is now a lie.

File: drake/solvers/MobyLCP.cpp [hunk 5]
```diff
@@ -161,44 +154,43 @@ bool MobyLCPSolver::solve(OptimizationProblem& prog) const {
...
+  prog.SetDecisionVariableValues(solution);
   return true;
 }
 
 /// Fast pivoting algorithm for denerate, monotone LCPs with few nonzero,
 /// nonbasic variables
-bool MobyLCPSolver::lcp_fast(
-    const Eigen::MatrixXd& M, const Eigen::VectorXd& q, Eigen::VectorXd* z,
-    double zero_tol) const {
+bool MobyLCPSolver::SolveLCPFast(const Eigen::MatrixXd& M,
```
Comment (jwnimmer-tri) [inline drake/solvers/MobyLCP.cpp]: Prefer SolveLcpFast to SolveLCPFast.
https://google.github.io/styleguide/cppguide.html#Function_Names

File: drake/solvers/MobyLCP.cpp [hunk 6]
```diff
@@ -306,42 +297,43 @@ bool MobyLCPSolver::lcp_fast(
...
 }
 
 /// Regularized wrapper around PPM I
-bool MobyLCPSolver::lcp_fast_regularized(
-    const Eigen::MatrixXd& M, const Eigen::VectorXd& q, Eigen::VectorXd* z,
-    int min_exp, unsigned step_exp, int max_exp,
-    double zero_tol) const {
-
-  LOG() << "MobyLCPSolver::lcp_fast_regularized() entered" << std::endl;
+bool MobyLCPSolver::SolveLCPFastRegularized(const Eigen::MatrixXd& M,
```
Comment (jwnimmer-tri) [inline drake/solvers/MobyLCP.cpp]: Prefer SolveLcpFast...

File: drake/solvers/MobyLCP.cpp [hunk 7]
```diff
@@ -497,15 +486,17 @@ bool MobyLCPSolver::checkLemkeTrivial(
...
+                                        Eigen::VectorXd* z) const {
   std::vector<unsigned>::iterator iiter;
   int idx;
   for (idx = 0, iiter = _bas.begin(); iiter != _bas.end(); iiter++, idx++) {
     (*z)(*iiter) = _x(idx);
   }
 
-  // TODO(sammy-tri) is there a more efficient way to resize and preserve the data?
+  // TODO(sammy-tri) is there a more efficient way to resize and preserve the
+  // data?
```
Comment (jwnimmer-tri) [inline drake/solvers/MobyLCP.cpp]: Cap

File: drake/solvers/MobyLCP.cpp [hunk 8]
```diff
@@ -804,28 +795,30 @@ bool MobyLCPSolver::lcp_lemke(
...
   return false;
 }
 
 /// Regularized wrapper around Lemke's algorithm
-bool MobyLCPSolver::lcp_lemke_regularized(
-    const Eigen::MatrixXd& M, const Eigen::VectorXd& q, Eigen::VectorXd* z,
-    int min_exp, unsigned step_exp, int max_exp,
-    double piv_tol, double zero_tol) const {
-  LOG() << "MobyLCPSolver::lcp_lemke_regularized() entered" << std::endl;
+bool MobyLCPSolver::SolveLCPLemkeRegularized(const Eigen::MatrixXd& M,
```
Comment (jwnimmer-tri) [inline drake/solvers/MobyLCP.cpp]: SolveLcp...

File: drake/solvers/MathematicalProgram.cpp (hunk 2 above)
Comment (sammy-tri) [inline drake/solvers/MathematicalProgram.cpp]: yup, that's clang-format's doing.  I'm not sure it's worth messing with since the formatting would presumably be different if it weren't in a comment anyway.

File: drake/solvers/MobyLCP.h [hunk 9]
```diff
@@ -13,47 +13,46 @@
...
+                                int max_exp = 1, double piv_tol = -1.0,
+                                double zero_tol = -1.0) const;
+  bool SolveLCPLemke(const Eigen::SparseMatrix<double>& M,
+                     const Eigen::VectorXd& q, Eigen::VectorXd* z,
+                     double piv_tol = -1.0, double zero_tol = -1.0) const;
+  bool SolveLCPLemkeRegularized(const Eigen::SparseMatrix<double>& M,
+                                const Eigen::VectorXd& q, Eigen::VectorXd* z,
+                                int min_exp = -20, unsigned step_exp = 4,
+                                int max_exp = 20, double piv_tol = -1.0,
+                                double zero_tol = -1.0) const;
```
Comment (jwnimmer-tri) [inline drake/solvers/MobyLCP.h]: I guess this is where I should have marked all of the SolveLcpFoo nits.

File: drake/solvers/MathematicalProgram.cpp (hunk 4 above)
Comment (sammy-tri) [inline drake/solvers/MathematicalProgram.cpp]: Fix pending in next commit

File: drake/solvers/MobyLCP.cpp (hunk 5 above)
Comment (sammy-tri) [inline drake/solvers/MobyLCP.cpp]: Fix pending in next commit

File: drake/solvers/MobyLCP.cpp (hunk 6 above)
Comment (sammy-tri) [inline drake/solvers/MobyLCP.cpp]: Fix pending...

**Comment by sammy-tri** [comment]
All tests have passed in debug mode.

File: drake/solvers/test/testMobyLCP.cpp [hunk 10]
```diff
@@ -34,15 +34,15 @@ Eigen::SparseMatrix<double> makeSparseMatrix(
 /// Run all non-regularized solvers.  If @p expected_z is an empty
 /// vector, outputs will only be compared against each other.
 template <typename Derived>
-void runBasicLCP(const Eigen::MatrixBase<Derived>& M, const Eigen::VectorXd& q,
+void RunBasicLCP(const Eigen::MatrixBase<Derived>& M, const Eigen::VectorXd& q,
```
Comment (jwnimmer-tri) [inline drake/solvers/test/testMobyLCP.cpp]: RunBasicLcp

File: drake/solvers/test/testMobyLCP.cpp [hunk 11]
```diff
@@ -58,31 +58,31 @@ void runBasicLCP(const Eigen::MatrixBase<Derived>& M, const Eigen::VectorXd& q,
...
+  result = l.SolveLCPLemke(M_sparse, q, &lemke_z);
   EXPECT_TRUE(CompareMatrices(lemke_z, expected_z, epsilon,
                               MatrixCompareType::absolute));
 }
 
 /// Run all regularized solvers.  If @p expected_z is an empty
 /// vector, outputs will only be compared against each other.
 template <typename Derived>
-void runRegularizedLCP(const Eigen::MatrixBase<Derived>& M,
+void RunRegularizedLCP(const Eigen::MatrixBase<Derived>& M,
```
Comment (jwnimmer-tri) [inline drake/solvers/test/testMobyLCP.cpp]: ...Lcp

**Comment by jwnimmer-tri** [comment]
My eyes are bleeding, but review complete.

**Comment by jwnimmer-tri** [comment]
> All tests have passed in debug mode.

Were all the files this PR touches compiled as part of that build?  Or are any of them guarded by have-matlab or have-solver cmake conditions?

**Comment by sammy-tri** [comment]
> Were all the files this PR touches compiled as part of that build? Or are any of them guarded by ? have-matlab or have-solver cmake conditions?

The only cmake conditions in effect for the files in this PR are WITH_SNOPT and WITH_NLOPT, both of which were enabled on my machine for the debug build/test run.

**Comment by liangfok** [comment]
Do you have MATLAB installed and configured to be used with Drake (i.e., with the mex compiler setup)?

**Comment by jwnimmer-tri** [comment]
The list of files touched here did not appear to have any dependence on matlab.

**Comment by sammy-tri** [comment]
> Do you have MATLAB installed and configured to be used with Drake (i.e., with the mex compiler setup)?

I do not, but I do not believe that these files are included in any mex libraries.

**Comment by liangfok** [comment]
OK I believe you.

**Comment by sammy-tri** [comment]
I don't know what just happened with drake005, but I'm leaving it:

File: drake/solvers/MathematicalProgram.cpp (hunk 2 above)
Comment (jwnimmer-tri) [inline drake/solvers/MathematicalProgram.cpp]: :headdesk:  Good enough.  Withdrawn.

**Comment by sammy-tri** [comment]
@jwnimmer-tri @david-german-tri I think this is ready to merge?

**Comment by jwnimmer-tri** [comment]
I don't have bits to push when "out-of-date with the base branch" exists.  Kicking over to @david-german-tri.

**Comment by david-german-tri** [comment]
LGTM++, I am so happy about this.  Thanks, @sammy-tri!

**Comment by jwnimmer-tri** [comment]
On reflection, this probably deserves a CHANGELOG.md mention.
@sammy-tri Do you want to whip up a tiny PR to do that?
