### PR TITLE
GraphOfConvexSets: don't try to display costs for convex restriction solutions

### LINKED ISSUE #20113: GetGraphvizString segfault / ell0 not captured
### What happened?

```
solver = ScsSolver()

options = GraphOfConvexSetsOptions()
options.preprocessing = True
options.max_rounded_paths = 10
options.convex_relaxation = True
options.solver = solver
result = G.SolveShortestPath(start, ro_aggregation, options)
```

I am using GCS with the MakeSemidefiniteRelaxation with the above settings. I get the result, then try to display it as follow:

```
from graphviz import Source
src = Source(G.GetGraphvizString(result=result, show_slacks=False, precision=2))
```
This errors with:
`*** ValueError: GetVariableValue: ell0 is not captured by the variable_index map.
`

If I put `show_slacks=True`, I get a segfault.

If I run the above with `show_slacks=True`, I get a segfault. I'm not really sure how to reduce my code to an MVP, so I'm hoping a GCS author can comment on why `ell0` might be erroring.

 

### Version

cce6c06531d94c376b79aeef124db0ed62a4c61a

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by RussTedrake**
Resolves #20113.

The ultimate solution will be to write the costs into the MathematicalProgramResult when solving the convex restriction. This is already listed with a TODO in SolveConvexRestriction; but will require some effort. For now, we shouldn't throw errors; we simply don't offer the cost display for that case.

+@richardrl for feature review.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20118)

### CODE REVIEW

File: geometry/optimization/graph_of_convex_sets.cc [hunk 1]
```diff
@@ -377,7 +377,15 @@ std::string GraphOfConvexSets::GetGraphvizString(
     graphviz << " [label=\"" << e->name();
     if (result) {
       graphviz << "\n";
-      graphviz << "cost = " << e->GetSolutionCost(*result);
+      if (e->ell_.size() > 0) {
+        // SolveConvexRestriction does not yet return the rewritten costs.
+        if (result->get_decision_variable_index()->count(e->ell_[0].get_id()) !=
```
Comment (richardrl) [inline geometry/optimization/graph_of_convex_sets.cc:382]: Why is the line on 382 necessary? 

GetSolutionCost sums the `ell_` vector in line 238, I think that summation will succeed if `ell_` is not size 0?

File: geometry/optimization/graph_of_convex_sets.cc [hunk 2]
```diff
@@ -377,7 +377,15 @@ std::string GraphOfConvexSets::GetGraphvizString(
...
+            0) {
+          graphviz << "cost = " << e->GetSolutionCost(*result);
+        }
+      } else {
+        graphviz << "cost = 0";
```
Comment (richardrl) [inline geometry/optimization/graph_of_convex_sets.cc:387]: Maybe we should print out a warning here that the cost = 0 is a dummy output while waiting on the new feature?

**Review by richardrl — COMMENTED** [review]
To summarize the current logic:
1. If there are no edge costs added, make the cost default to 0.
2. If there are edge costs, but edge cost is not present in the result - do nothing. I think this is fine for now, better than erroneously displaying cost = 0.
3. If there are edge costs, and the edge cost is present in the result, then return the actual result cost.

LGTM

File: geometry/optimization/graph_of_convex_sets.cc (hunk 1 above)
Comment (richardrl) [inline geometry/optimization/graph_of_convex_sets.cc:382]: This seems fine but I wonder why we don't combine the two boolean conditions:

```
if ((e->ell_.size() > 0) &&
      (result->get_decision_variable_index()->count(e->ell_[0].get_id()) !=
            0)) {
        // SolveConvexRestriction does not yet return the rewritten costs.
          graphviz << "cost = " << e->GetSolutionCost(*result);
      }
```
this also passes the unit test

**Review by richardrl — APPROVED** [review]

**Review by EricCousineau-TRI — COMMENTED** [review]
+@EricCousineau-TRI for platform :lgtm: given Richard's review

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20118#-:-NdkQOEe7jr6iwteJo3N:b-wbc2cx)* status: needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
+@hongkai-dai Would you be OK serving as additional review to have 2 authorized reviewers?
(I can use the "single reviewer" label, but would prefer this just to be on the safe side)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20118#-:-NdkQWhYATyxKqS4gsw7:b-odw7ba)* status: LGTM missing from assignee hongkai-dai

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake/20118#-:-NdkYSOs1x-q8biiIDDV:bg7igkv)* status: :shipit: complete! all discussions resolved, LGTM from assignees EricCousineau-TRI(platform),hongkai-dai
