### PR TITLE
Fixed drake joint

### LINKED ISSUE #822: testURDF fails now that it is parsing every urdf in drake
There seems to be a few independent failures

systems/plants/test/testURDFmex (unknown issue)
```
error_id = MATLAB:badsubscript
error_message = Index exceeds matrix dimensions.
is_segfault = 0
```
```Matlab

                           < M A T L A B (R) >
                 Copyright 1984-2012 The MathWorks, Inc.
                   R2012b (8.0.0.783) 64-bit (glnxa64)
                             August 22, 2012


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

To reproduce this test use rng(565038455,'twister')

[Warning: Disabling autosave for simulink blocks (to avoid generating a
lot of
*.mdl.autosave files in your directory.  If you aren't a regular Simulink
user
and don't want this disabled, comment out this section in addpath_drake.
To disable this warning in the future, add
  warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m] 
[> In addpath_drake at 74
 In addpath_drake at 4] 
testing
/tmp/drake-master-18823/drake/systems/plants/constraint/test/valve_task_wall.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: The bodies listed below each contained at least one
RigidBodyCylinder
as a collision geometry:

	Body Idx	Body Name
	3:
       valve_base+Spokes_2+Spokes_1+Spokes_0+RING_7+RING_6+RING_5+RING_4+RING_3+RING_2+RING_1+RING_0
       	4:
       valve_base10+Spokes10_2+Spokes10_1+Spokes10_0+RING10_7+RING10_6+RING10_5+RING10_4+RING10_3+RING10_2+RING10_1+RING10_0
       	5:
       valve_base11+Spokes11_2+Spokes11_1+Spokes11_0+RING11_7+RING11_6+RING11_5+RING11_4+RING11_3+RING11_2+RING11_1+RING11_0
       	6:
       valve_base2+Spokes2_2+Spokes2_1+Spokes2_0+RING2_7+RING2_6+RING2_5+RING2_4+RING2_3+RING2_2+RING2_1+RING2_0
       	7:
       valve_base3+Spokes3_2+Spokes3_1+Spokes3_0+RING3_7+RING3_6+RING3_5+RING3_4+RING3_3+RING3_2+RING3_1+RING3_0
       	8:
       valve_base4+Spokes4_2+Spokes4_1+Spokes4_0+RING4_7+RING4_6+RING4_5+RING4_4+RING4_3+RING4_2+RING4_1+RING4_0
       	9:
       valve_base5+Spokes5_2+Spokes5_1+Spokes5_0+RING5_7+RING5_6+RING5_5+RING5_4+RING5_3+RING5_2+RING5_1+RING5_0
       	10:
       valve_base6+Spokes6_2+Spokes6_1+Spokes6_0+RING6_7+RING6_6+RING6_5+RING6_4+RING6_3+RING6_2+RING6_1+RING6_0
       	11:
       valve_base7+Spokes7_2+Spokes7_1+Spokes7_0+RING7_7+RING7_6+RING7_5+RING7_4+RING7_3+RING7_2+RING7_1+RING7_0
       	12:
       valve_base8+Spokes8_2+Spokes8_1+Spokes8_0+RING8_7+RING8_6+RING8_5+RING8_4+RING8_3+RING8_2+RING8_1+RING8_0
       	13:
       valve_base9+Spokes9_2+Spokes9_1+Spokes9_0+RING9_7+RING9_6+RING9_5+RING9_4+RING9_3+RING9_2+RING9_1+RING9_0


These collision geometries were replaced by RigidBodyCapsule objects, as
the
cylinder contact geometry is less robust.

To prevent this replacement, construct your manipulator with:

options.replace_cylinders_with_capsules = false;
r = RigidBodyManipulator(...,options);

To silence this warning, construct your manipulator with:

w = warning('off','Drake:RigidBodyManipulator:ReplacedCylinder');
r = RigidBodyManipulator(...);
warning(w)

] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.adjustCollisionGeometry at 2415
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 826
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
skipping RING_0 because it's been welded
skipping RING_1 because it's been welded
skipping RING_2 because it's been welded
skipping RING_3 because it's been welded
skipping RING_4 because it's been welded
skipping RING_5 because it's been welded
skipping RING_6 because it's been welded
skipping RING_7 because it's been welded
skipping Spokes_0 because it's been welded
skipping Spokes_1 because it's been welded
testing
/tmp/drake-master-18823/drake/systems/plants/test/brick_point_contact.urdf
testing
/tmp/drake-master-18823/drake/systems/plants/test/testRigidBodyWingWithControlSurface.urdf
Constructing a new airfoil
Using a flat plate airfoil.
Constructing a new airfoil
Using a flat plate airfoil.
Constructing a new airfoil
Using a flat plate airfoil.
Constructing a new airfoil
Using a flat plate airfoil.
Constructing a new airfoil
Using a flat plate airfoil.
Index exceeds matrix dimensions.

Error in testURDFmex (line 86)
 Bcpp =
reshape(Hcpp{1}(index+(1:getNumInputs(r)*num_vc)),getNumInputs(r),num_vc)';

Error in fevalPackageSafe (line 21)
 feval(f);


<test_name>systems/plants/test/testURDFmex</test_name>
<error_id>MATLAB:badsubscript</error_id> <error_message>Index exceeds
matrix dimensions.</error_message> 


```

and 

systems/plants/test/testURDFmex (unknown issue)
```
error_id = Drake:ValueCheck
error_message = Values don't match.
   Index       Value       Desired Value
  -------     --------    ---------------
    (1,1)     8.000000       24.000000
    (5,1)    -8.000000      -24.000000
    (7,1)    -8.000000      -24.000000
    (8,1)    -2.000000       -6.000000
    (3,3)     8.000000        8.600000
    (1,5)    -8.000000      -24.000000
    (5,5)    10.600000       32.000000
    (7,5)    10.600000       32.000000
    (8,5)     3.300000       10.000000
    (1,7)    -8.000000      -24.000000
    (5,7)    10.600000       32.000000
    (7,7)    10.600000       32.000000
    (8,7)     3.300000       10.000000
    (1,8)    -2.000000       -6.000000
    (5,8)     3.300000       10.000000
    (7,8)     3.300000       10.000000
    (8,8)     1.300000        4.000000

is_segfault = 0
```
```Matlab

                           < M A T L A B (R) >
                 Copyright 1984-2014 The MathWorks, Inc.
                   R2014a (8.3.0.532) 64-bit (glnxa64)
                            February 11, 2014


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

To reproduce this test use rng(567354423,'twister')

[Warning: Disabling autosave for simulink blocks (to avoid generating a
lot of
*.mdl.autosave files in your directory.  If you aren't a regular Simulink
user
and don't want this disabled, comment out this section in addpath_drake.
To disable this warning in the future, add
  warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m] 
[> In addpath_drake at 74
 In addpath_drake at 4] 
testing /tmp/drake-precompiled-2186/drake/examples/Acrobot/Acrobot.urdf
testing
/tmp/drake-precompiled-2186/drake/examples/Acrobot/test/AcrobotWParams.urdf
Calling addpath_spotless
this model has parameters (not implemented in c++ yet), so will be skipped
testing
/tmp/drake-precompiled-2186/drake/examples/UnderwaterAcrobot/UnderwaterAcrobot.urdf
Error using valuecheck (line 78)
Values don't match.
   Index       Value       Desired Value
  -------     --------    ---------------
    (1,1)     8.000000       24.000000
    (5,1)    -8.000000      -24.000000
    (7,1)    -8.000000      -24.000000
    (8,1)    -2.000000       -6.000000
    (3,3)     8.000000        8.600000
    (1,5)    -8.000000      -24.000000
    (5,5)    10.600000       32.000000
    (7,5)    10.600000       32.000000
    (8,5)     3.300000       10.000000
    (1,7)    -8.000000      -24.000000
    (5,7)    10.600000       32.000000
    (7,7)    10.600000       32.000000
    (8,7)     3.300000       10.000000
    (1,8)    -2.000000       -6.000000
    (5,8)     3.300000       10.000000
    (7,8)     3.300000       10.000000
    (8,8)     1.300000        4.000000


Error in testURDFmex (line 100)
 valuecheck(Hcpp,H,tol);

Error in fevalPackageSafe (line 21)
 feval(f);


<test_name>systems/plants/test/testURDFmex</test_name>
<error_id>Drake:ValueCheck</error_id> <error_message>Values don't match.
   Index       Value       Desired Value
  -------     --------    ---------------
    (1,1)     8.000000       24.000000
    (5,1)    -8.000000      -24.000000
    (7,1)    -8.000000      -24.000000
    (8,1)    -2.000000       -6.000000
    (3,3)     8.000000        8.600000
    (1,5)    -8.000000      -24.000000
    (5,5)    10.600000       32.000000
    (7,5)    10.600000       32.000000
    (8,5)     3.300000       10.000000
    (1,7)    -8.000000      -24.000000
    (5,7)    10.600000       32.000000
    (7,7)    10.600000       32.000000
    (8,7)     3.300000       10.000000
    (1,8)    -2.000000       -6.000000
    (5,8)     3.300000       10.000000
    (7,8)     3.300000       10.000000
    (8,8)     1.300000        4.000000
</error_message> 


```

systems/plants/test/testURDFmex (unknown issue)
```
error_id = Drake:ValueCheck
error_message = NANs don't match. val has no NANsbut desired_val has them
at 
(1,2)(3,1)(1,1)

is_segfault = 0
```
```Matlab

                           < M A T L A B (R) >
                 Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (maci64)
                            February 11, 2014


To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.

To reproduce this test use rng(565550884,'twister')

[Warning: Disabling autosave for simulink blocks (to avoid generating a
lot of
*.mdl.autosave files in your directory.  If you aren't a regular Simulink
user
and don't want this disabled, comment out this section in addpath_drake.
To disable this warning in the future, add
  warning('off','Drake:DisablingSimulinkAutosave')
to your matlab startup.m] 
[> In addpath_drake at 74
 In addpath_drake at 4] 
testing /private/tmp/drake-master-12769/drake/examples/Acrobot/Acrobot.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Acrobot/test/AcrobotWParams.urdf
Calling addpath_spotless
this model has parameters (not implemented in c++ yet), so will be skipped
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/atlas_convex_hull.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/atlas_minimal_contact.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/block_hand.urdf
testing /private/tmp/drake-master-12769/drake/examples/Atlas/urdf/door.urdf
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
skipping Right_Jamb because it's been welded
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/drill_frame.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/robotiq.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: still need to add time derivatives of position constraints] 
[> In WarningManager>WarningManager.warnOnce at 21
 In Manipulator.Manipulator>Manipulator.updatePositionEqualityConstraint
at 191
 In Manipulator.Manipulator>Manipulator.addPositionEqualityConstraint at
167
 In RigidBodyLoop>RigidBodyLoop.updateConstraints at 27
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 869
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
skipping finger_1_link_0 because it's been welded
skipping finger_2_link_0 because it's been welded
skipping finger_middle_link_0 because it's been welded
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/robotiq_box.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Atlas/urdf/valve_wall.urdf
[Warning: The bodies listed below each contained at least one
RigidBodyCylinder
as a collision geometry:

	Body Idx	Body Name
	3:		Lever
	4:		Valve_18
	5:		Valve_8


These collision geometries were replaced by RigidBodyCapsule objects, as
the
cylinder contact geometry is less robust.

To prevent this replacement, construct your manipulator with:

options.replace_cylinders_with_capsules = false;
r = RigidBodyManipulator(...,options);

To silence this warning, construct your manipulator with:

w = warning('off','Drake:RigidBodyManipulator:ReplacedCylinder');
r = RigidBodyManipulator(...);
warning(w)

] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.adjustCollisionGeometry at 2415
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 826
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing
/private/tmp/drake-master-12769/drake/examples/FurutaPendulum/FurutaPendulum.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Glider/GliderBalanced.urdf
Constructing a new airfoil
Using a flat plate airfoil.
Constructing a new airfoil
Using a flat plate airfoil.
testing
/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/ATI_sensor.urdf
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/ATI_sensor.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing
/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/irb_140.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/base_link.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/link1.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/link2.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/link3.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/link4.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/link5.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: SOLID name in
"/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/meshes/link6.stl"
STL file starts with invalid VRML identifier character.] 
[> In stl2vrml.stl2vrml>stl2vrml.stl2faces at 501
 In stl2vrml.stl2vrml>stl2vrml.convert_stl2vrml at 227
 In stl2vrml at 80
 In RigidBodyMesh>RigidBodyMesh.convertToWRL at 73
 In RigidBodyMesh>RigidBodyMesh.loadFile at 29
 In RigidBodyMesh>RigidBodyMesh.getPoints at 66
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.createMexPointer at 2093
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 831
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing
/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/irb_140_robotiq.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: still need to add time derivatives of position constraints] 
[> In WarningManager>WarningManager.warnOnce at 21
 In Manipulator.Manipulator>Manipulator.updatePositionEqualityConstraint
at 191
 In Manipulator.Manipulator>Manipulator.addPositionEqualityConstraint at
167
 In RigidBodyLoop>RigidBodyLoop.updateConstraints at 27
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 869
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
skipping palm because it's been welded
skipping finger_1_link_0 because it's been welded
skipping finger_2_link_0 because it's been welded
skipping finger_middle_link_0 because it's been welded
testing
/private/tmp/drake-master-12769/drake/examples/IRB140/urdf/irb_140_robotiq_ati.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: 3D loop joints do not properly enforce the joint axis
constraint.
(they perform more like a ball joint)] 
[> In RigidBodyLoop>RigidBodyLoop.parseURDFNode at 91
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 109
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: still need to add time derivatives of position constraints] 
[> In WarningManager>WarningManager.warnOnce at 21
 In Manipulator.Manipulator>Manipulator.updatePositionEqualityConstraint
at 191
 In Manipulator.Manipulator>Manipulator.addPositionEqualityConstraint at
167
 In RigidBodyLoop>RigidBodyLoop.updateConstraints at 27
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 869
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
skipping palm because it's been welded
skipping finger_1_link_0 because it's been welded
skipping finger_2_link_0 because it's been welded
skipping finger_middle_link_0 because it's been welded
testing
/private/tmp/drake-master-12769/drake/examples/KneedCompassGait/KneedCompassGait.urdf
skipping left_upper_leg because it's been welded
skipping left_upper_leg_mass because it's been welded
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/Pendulum.urdf
[Warning: The bodies listed below each contained at least one
RigidBodyCylinder
as a collision geometry:

	Body Idx	Body Name
	3:		arm+arm_com


These collision geometries were replaced by RigidBodyCapsule objects, as
the
cylinder contact geometry is less robust.

To prevent this replacement, construct your manipulator with:

options.replace_cylinders_with_capsules = false;
r = RigidBodyManipulator(...,options);

To silence this warning, construct your manipulator with:

w = warning('off','Drake:RigidBodyManipulator:ReplacedCylinder');
r = RigidBodyManipulator(...);
warning(w)

] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.adjustCollisionGeometry at 2415
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 826
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p1.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p10.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p11.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p12.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p2.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p3.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p4.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p5.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p6.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p7.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p8.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/p9.urdf
testing
/private/tmp/drake-master-12769/drake/examples/Pendulum/test/PendulumWithFriction.urdf
[Warning: The bodies listed below each contained at least one
RigidBodyCylinder
as a collision geometry:

	Body Idx	Body Name
	3:		arm+arm_com


These collision geometries were replaced by RigidBodyCapsule objects, as
the
cylinder contact geometry is less robust.

To prevent this replacement, construct your manipulator with:

options.replace_cylinders_with_capsules = false;
r = RigidBodyManipulator(...,options);

To silence this warning, construct your manipulator with:

w = warning('off','Drake:RigidBodyManipulator:ReplacedCylinder');
r = RigidBodyManipulator(...);
warning(w)

] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.adjustCollisionGeometry at 2415
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 826
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
testing /private/tmp/drake-master-12769/drake/examples/PR2/pr2.urdf
[Warning: RigidBodyManipulator: velocity limits are not supported yet] 
[> In WarningManager>WarningManager.warnOnce at 21
 In RigidBodyManipulator.addRobotFromURDF>parseJoint at 356
 In RigidBodyManipulator.addRobotFromURDF>parseRobot at 104
 In RigidBodyManipulator.addRobotFromURDF at 54
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Link l_gripper_l_finger_tip_frame has zero inertia (even though
gravity is on and it's not a fixed joint) and will be removed] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.removeFixedJoints at 2316
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 666
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Link r_gripper_l_finger_tip_frame has zero inertia (even though
gravity is on and it's not a fixed joint) and will be removed] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.removeFixedJoints at 2316
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 666
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: The bodies listed below each contained at least one
RigidBodyCylinder
as a collision geometry:

	Body Idx	Body Name
	4:		fl_caster_l_wheel_link
	5:		fl_caster_r_wheel_link
	7:		fr_caster_l_wheel_link
	8:		fr_caster_r_wheel_link
	10:		bl_caster_l_wheel_link
	11:		bl_caster_r_wheel_link
	13:		br_caster_l_wheel_link
	14:		br_caster_r_wheel_link


These collision geometries were replaced by RigidBodyCapsule objects, as
the
cylinder contact geometry is less robust.

To prevent this replacement, construct your manipulator with:

options.replace_cylinders_with_capsules = false;
r = RigidBodyManipulator(...,options);

To silence this warning, construct your manipulator with:

w = warning('off','Drake:RigidBodyManipulator:ReplacedCylinder');
r = RigidBodyManipulator(...);
warning(w)

] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.adjustCollisionGeometry at 2415
 In RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile
at 826
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
[Warning: Contact is not supported by the dynamics methods of this class.
Consider using TimeSteppingRigidBodyManipulator or
HybridPlanarRigidBodyManipulator] 
[> In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.compile at
882
 In RigidBodyManipulator.addRobotFromURDF at 59
 In
RigidBodyManipulator.RigidBodyManipulator>RigidBodyManipulator.RigidBodyManipulator at 73
 In testURDFmex at 22
 In fevalPackageSafe at 21] 
skipping base_link because it's been welded
skipping base_laser_link because it's been welded

desired_val =

  NaN
  NaN
  NaN
    0
    0
    0

Error using valuecheck (line 78)
NANs don't match. val has no NANsbut desired_val has them at 
(1,2)(3,1)(1,1)


Error in testURDFmex (line 49)
   valuecheck(pt,x,tol);

Error in fevalPackageSafe (line 21)
 feval(f);


<test_name>systems/plants/test/testURDFmex</test_name>
<error_id>Drake:ValueCheck</error_id> <error_message>NANs don't match. val
has no NANsbut desired_val has them at 
(1,2)(3,1)(1,1)
</error_message> 


```

<matlab_test>strcmp(test_name,'systems/plants/test/testURDFmex')</matlab_test>

### PR DESCRIPTION
**Pull request by RussTedrake**
Adds explicit support for fixed joints in the c++ kinematics.  (with @tkoolen)
Resolves #822 by fixing a fairly ridiculous number of little parsing bugs (in matlab and c++!).  testURDFmex now passes for all urdfs in drake and with random q.  
but also revealed a new(?) bug in the use_new_kinsol dynamics when v is random.

### CODE REVIEW

File: systems/plants/RigidBodyManipulator.cpp [hunk 1]
```diff
@@ -1088,59 +1107,71 @@ void RigidBodyManipulator::doKinematicsNew(const MatrixBase<DerivedQ>& q, const
...
-          // Sdotv
-          auto dSdotVdqi = compute_gradients ? &body.dSdotVdqi : nullptr;
-          auto dSdotVdvi = compute_gradients ? &body.dSdotVdvi : nullptr;
-          joint.motionSubspaceDotTimesV(q_body, v_body, body.SdotV, dSdotVdqi, dSdotVdvi);
-
-          // Jdotv
-          auto joint_accel = crossSpatialMotion(body.twist, joint_twist.value());
-          joint_accel += transformSpatialMotion(body.T_new, body.SdotV);
-          body.JdotV = body.parent->JdotV + joint_accel;
+        if (joint.getNumVelocities()==0) { // for fixed joints
```
Comment (RussTedrake) [inline systems/plants/RigidBodyManipulator.cpp]: the diff did a horrible job on this one.  I've added this if() case, but the code in the else (which was always run before) is unchanged.

Comment (tkoolen) [inline systems/plants/RigidBodyManipulator.cpp]: Might be because the indentation is wrong, could you fix it?

Comment (tkoolen) [inline systems/plants/RigidBodyManipulator.cpp]: Never mind, misread it on my tiny phone screen

File: systems/plants/test/testURDFmex.m [hunk 2]
```diff
@@ -14,76 +14,117 @@
...
-  r = RigidBodyManipulator(urdffile,struct('floating',true,'use_new_kinsol',true));
-
+  w = warning('off','Drake:RigidBodyManipulator:UnsupportedVelocityLimits');
+  warning('off','Drake:RigidBodyManipulator:UnsupportedContactPoints');
+  warning('off','Drake:RigidBodyManipulator:ReplacedCylinder');
+  try 
+    r = RigidBodyManipulator(urdffile,struct('floating',true,'use_new_kinsol',true));
+  catch ex
+    if strncmp(ex.identifier,'Drake:MissingDependency:',24)
+      disp(' skipping due to a missing dependency');
```
Comment (tkoolen) [inline systems/plants/test/testURDFmex.m]: What is the magic number 24 here? Could you extract it out into a named variable?

File: systems/plants/test/testURDFmex.m [hunk 3]
```diff
@@ -14,76 +14,117 @@
   error('Drake:MissingDependency','testURDFmex requires that urdfManipulatorDynamicsTest is built (from the command line).  skipping this test');
 end
 
-tol = 1e-2; % low tolerance because i'm writing finite precision strings to and from the ascii terminal
+tol = .1; % low tolerance because i'm writing finite precision strings to and from the ascii terminal
```
Comment (tkoolen) [inline systems/plants/test/testURDFmex.m]: .1 is very high. Can this really be attributed to precision of printing as a string?

File: systems/plants/joints/FixedAxisOneDoFJoint.h [hunk 4]
```diff
@@ -37,6 +40,9 @@ class DLLEXPORT_DRAKEJOINT FixedAxisOneDoFJoint : public DrakeJoint
 
   virtual void v2qdot(const Eigen::Ref<const Eigen::VectorXd>& q, Eigen::MatrixXd& v_to_qdot, Eigen::MatrixXd* dv_to_qdot) const; //override;
 
+  void setDynamics(double damping, double coulomb_friction, double coulomb_window);
```
Comment (tkoolen) [inline systems/plants/joints/FixedAxisOneDoFJoint.h]: Why not have separate setters for these?

File: systems/plants/test/testURDFmex.m (hunk 3 above)
Comment (tkoolen) [inline systems/plants/test/testURDFmex.m]: .1 is very low. Can this really be attributed to precision of printing a double?

File: systems/plants/joints/FixedAxisOneDoFJoint.h (hunk 4 above)
Comment (RussTedrake) [inline systems/plants/joints/FixedAxisOneDoFJoint.h]: just trying to type less. i'm ok with either one.

File: systems/plants/test/testURDFmex.m (hunk 2 above)
Comment (RussTedrake) [inline systems/plants/test/testURDFmex.m]: the length of the string 'Drake:MissingDependency:'

**Comment by RussTedrake** [comment]
since the only style comments left are on a test which is scheduled for deletion, i will pull as is.  thanks @tkoolen .
