### PR TITLE
KinematicsCache object, updated

### LINKED ISSUE #585: testIndividualCentersOfPressure fails
i believe it fails reliably, even though it looks like it's numerically close:

Site: DRAKE003
Build Name: precompiled-RobotLocomotion-master
Build Server Directory: C:\cygwin64\tmp\drake-precompiled-12095\drake
CDash: http://kobol.csail.mit.edu/cd/index.php?project=Drake&date=20141127

Most recent commits to drake included in this build:
```
4367981 Merge pull request #581 from RussTedrake/wintests
aa88877 update cmake.  hopefully works for all this time.
ee44891 update cmake
9feda7b update cmake
96abcc9 another attempt at cmake builds for all platforms
```

examples/Atlas/test/testIndividualCentersOfPressure (unknown issue)
```
error_id = Drake:ValueCheck
error_message = Values don't match.  Expected 
[-1.3505484925705 -1.90034872665083;1.60086581345863
1.61466215190119;-9.80153558935972 -9.29230038365085]
but got 
[-1.45661172175738 -1.98643902446545;1.64631043532796
1.63446299810698;-9.81134875986639 -9.34511885116823]
is_segfault = 0
```

<matlab_test>strcmp(test_name,'examples/Atlas/test/testIndividualCentersOfPressure') && strcmp(error_id,'Drake:ValueCheck')</matlab_test>

### LINKED ISSUE #1167: Separate out doKinematics cache variables into a class
Currently, cache from the `doKinematics` method lives in `RigidBodyManipulator` and the `RigidBody` instances in the `bodies` field of `RigidBodyManipulator`, as Matrix<double, ...> variables. To support polynomial/symbolic/TaylorVar dynamics in C++, we should extract the cache variables out and put them into a separate object, which would be templated with the scalar type (double, Polynomial, TrigPoly, ...) as the template variable. The class could be called e.g. `KinematicsCache`. This also allows storage of multiple kinematics caches, useful for e.g. kinematics constraints that need to hold at multiple times during a trajectory optimization. It will also clean things up a lot.

### PR DESCRIPTION
**Pull request by tkoolen**
See https://github.com/RobotLocomotion/drake/pull/1286 (I couldn't reopen because I force pushed after rebasing).

Profling showed that creating new DrakeMexPointers every time you call doKinematics is too expensive. I'm now creating two default KinematicsCache DrakeMexPointers (one with gradients, one without) upon creation of a RigidBodyManipulator in Matlab. These will get reused by doKinematics unless you set options.kinematics_cache_ptr_to_use to another KinematicsCache DrakeMexPointer. I added a mex function to explicitly create a new KinematicsCache.

In addition, I tried to reduce the need for malloc a bit by making the dynamic size members of KinematicsCacheElement have a fixed *maximum* size. This means that these matrices will get allocated on the stack, yet it's possible to resize them up to their maximum size.

Fixes #1167.
Fixes #585 by just getting rid of the Matlab code + test.

### CODE REVIEW

**Comment by tkoolen** [comment]
Rebased onto master.

File: drake/systems/controllers/QPController.m [hunk 1]
```diff
@@ -346,13 +346,13 @@
 
       if include_angular_momentum
         A = centroidalMomentumMatrix(r, kinsol);
-        Adot_times_v = centroidalMomentumMatrixDotTimesVmex(r, kinsol);
```
Comment (rdeits) [inline drake/systems/controllers/QPController.m]: sorry you had to update these--this file's scheduled for deletion as soon as I finish porting all the Atlas examples to the new controller

File: drake/systems/controllers/QPControllermex.cpp [hunk 2]
```diff
@@ -236,7 +236,7 @@ void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
 
   MatrixXd R_DQyD_ls = R_ls + D_ls.transpose()*Qy*D_ls;
 
-  pdata->r->doKinematics(q, qd);
```
Comment (rdeits) [inline drake/systems/controllers/QPControllermex.cpp]: ...and this one

File: drake/systems/controllers/bodyMotionControlmex.cpp [hunk 3]
```diff
@@ -70,10 +70,10 @@ void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
   assert(mxGetM(prhs[narg])==6); assert(mxGetN(prhs[narg])==1);
   Map< Vector6d > body_vdot_des(mxGetPrSafe(prhs[narg++]));
 
-  pdata->r->doKinematics(q, qd);
```
Comment (rdeits) [inline drake/systems/controllers/bodyMotionControlmex.cpp]: ...and this one

File: drake/systems/controllers/controlUtil.cpp [hunk 4]
```diff
@@ -278,7 +278,7 @@ Matrix<bool, Dynamic, 1> getActiveSupportMask(RigidBodyManipulator* r, void* map
       if (contact_threshold == -1) {
         kin_contact = true;
       } else {
-        contactPhi(r,se,map_ptr,phi,terrain_height);
```
Comment (rdeits) [inline drake/systems/controllers/controlUtil.cpp]: this will cause conflicts with #1315 but should be easy to resolve

File: drake/util/drakeGeometryUtil.h [hunk 5]
```diff
@@ -96,48 +153,241 @@ Eigen::Quaternion<typename Derived::Scalar> quat2eigenQuaternion(const Eigen::Ma
...
+    ret.value() = expmap2quatDegenerate(v, theta);
+    if(gradient_order>0)
+    {
+      ret.gradient().value() = dexpmap2quatDegenerate(v, theta);
+      if(gradient_order>1)
+      {
+        ret.gradient().gradient().value() = ddexpmap2quatDegenerate(v, theta);
+        if(gradient_order>2)
+        {
+          throw std::runtime_error("expmap2quat does not support gradient order larger than 2");
```
Comment (patmarion) [inline drake/util/drakeGeometryUtil.h]: should these checks be assertions instead of exceptions?

File: drake/util/expmap2quat.h [hunk 6]
```diff
@@ -1,8 +1,19 @@
...
+#undef DLLEXPORT
+#if defined(WIN32) || defined(WIN64)
+#if defined(drakeGeometryUtil_EXPORTS)
+#define DLLEXPORT __declspec( dllexport )
+#else
+#define DLLEXPORT __declspec( dllimport )
+#endif
+#else
+#define DLLEXPORT
+#endif
```
Comment (patmarion) [inline drake/util/expmap2quat.h]: have you thought about using a common header, like drakeGeometryUtilExports.h to store these definitions?

File: drake/systems/plants/inverseDynamicsmex.cpp [hunk 7]
```diff
@@ -24,21 +24,24 @@ void mexFunction(int nlhs, mxArray *plhs[],int nrhs, const mxArray *prhs[]) {
...
   const mxArray* f_ext_matlab = nullptr;
   const mxArray* vd_matlab = nullptr;
   const mxArray* df_ext_matlab = nullptr;
   const mxArray* dvd_matlab = nullptr;
-  if (nrhs > 1)
-    f_ext_matlab = prhs[1];
   if (nrhs > 2)
-    vd_matlab = prhs[2];
+    f_ext_matlab = prhs[arg_num++];
   if (nrhs > 3)
```
Comment (patmarion) [inline drake/systems/plants/inverseDynamicsmex.cpp]: In drake c++, I've seen single statement if conditionals that span two lines using  braces and without braces.  Is there a policy on this usage?

File: drake/systems/plants/KinematicsCache.h [hunk 8]
```diff
@@ -0,0 +1,184 @@
...
+public:
+  int gradient_order;
+  bool position_kinematics_cached;
+  bool gradients_cached;
+  bool velocity_kinematics_cached;
+  bool jdotV_cached;
+  int cached_inertia_gradients_order;
+
+public:
+  KinematicsCache(const std::vector<std::shared_ptr<RigidBody>>& bodies, int gradient_order) :
```
Comment (patmarion) [inline drake/systems/plants/KinematicsCache.h]: enum? :)

File: drake/systems/plants/KinematicsCache.h [hunk 9]
```diff
@@ -0,0 +1,184 @@
...
+class KinematicsCache
+{
+private:
+  std::unordered_map<RigidBody const *, KinematicsCacheElement<Scalar>> elements;
+  Eigen::Matrix<Scalar, Eigen::Dynamic, 1> q;
+  Eigen::Matrix<Scalar, Eigen::Dynamic, 1> v;
+  bool velocity_vector_valid;
+
+public:
+  int gradient_order;
```
Comment (hongkai-dai) [inline drake/systems/plants/KinematicsCache.h]: Shall we write a getter/setter for gradient_order, to avoid the user mistakenly set the gradient_order?

Comment (patmarion) [inline drake/systems/plants/KinematicsCache.h]: should this be const?

File: drake/systems/plants/inverseDynamicsmex.cpp (hunk 7 above)
Comment (rdeits) [inline drake/systems/plants/inverseDynamicsmex.cpp]: I bet apple wishes they hadn't allowed the no-brace style :wink: 

https://www.imperialviolet.org/2014/02/22/applebug.html

File: drake/systems/plants/KinematicsCache.h [hunk 10]
```diff
@@ -0,0 +1,184 @@
...
+  bool position_kinematics_cached;
```
Comment (patmarion) [inline drake/systems/plants/KinematicsCache.h]: not a fan of public member variables :-(

File: drake/systems/controllers/QPController.m (hunk 1 above)
Comment (tkoolen) [inline drake/systems/controllers/QPController.m]: No worries. Thanks for https://github.com/RobotLocomotion/drake/pull/1316!

File: drake/util/drakeGeometryUtil.h (hunk 5 above)
Comment (tkoolen) [inline drake/util/drakeGeometryUtil.h]: Just FYI, I didn't write this code, just moved it from the source file to the header.
I think you're right. However, if we're going to be getting rid of GradientVar and our user gradients completely and relying totally on AutoDiffScalar, this code will be removed in the process.
I can change it for now.

File: drake/util/expmap2quat.h (hunk 6 above)
Comment (tkoolen) [inline drake/util/expmap2quat.h]: I think these also need to be in drakeGeometryUtil (what's so special about these expmap functions?), but wanted to keep the number of changes in check at least somewhat.

File: drake/systems/plants/inverseDynamicsmex.cpp (hunk 7 above)
Comment (tkoolen) [inline drake/systems/plants/inverseDynamicsmex.cpp]: We need a proper code style guide. Our current one doesn't even mention this. Until we have one, it's user preference.

File: drake/systems/plants/KinematicsCache.h (hunk 8 above)
Comment (tkoolen) [inline drake/systems/plants/KinematicsCache.h]: what are you referring to? gradient_order since it only has two options? If so, gradient_order (here and everywhere in our codebase) will be removed when we switch to AutoDiffScalar based gradients.

File: drake/systems/plants/KinematicsCache.h (hunk 9 above)
Comment (tkoolen) [inline drake/systems/plants/KinematicsCache.h]: Both right. Was lazy. Will fix.

File: drake/systems/plants/KinematicsCache.h (hunk 10 above)
Comment (tkoolen) [inline drake/systems/plants/KinematicsCache.h]: Will fix.

File: drake/systems/plants/KinematicsCache.h (hunk 8 above)
Comment (hongkai-dai) [inline drake/systems/plants/KinematicsCache.h]: I do not think gradient_order should be enum. Although we have not encountered it yet, I can imagine in the future, we want higher order of gradient (Heassian if we want to do some sensitivity analysis of the trajectory). So we should support higher orders here.

File: drake/systems/plants/KinematicsCache.h (hunk 9 above)
Comment (tkoolen) [inline drake/systems/plants/KinematicsCache.h]: I think the need for these getters and setters has made it even more clear to me that all of the doKinematics functionality needs to move to KinematicsCache. I'll do the getters/setters thing for this pull request, and move the functionality in an upcoming pull request.

**Comment by RussTedrake** [comment]
the failures on travis look real (only caught by building in debug mode. wow)

File: drake/systems/plants/RigidBodyManipulator.h [hunk 11]
```diff
@@ -97,46 +99,256 @@ class DLLEXPORT_RBM RigidBodyManipulator
...
+  KinematicsCache<typename DerivedQ::Scalar> doKinematics(const MatrixBase<DerivedQ>& q, const MatrixBase<DerivedV>& v, int gradient_order = 0, bool compute_JdotV = true) {
+    KinematicsCache<typename DerivedQ::Scalar> ret(bodies, gradient_order);
+    ret.initialize(q, v);
+    doKinematics(ret, compute_JdotV);
+    return ret;
+  }
 
-  double getMass(const std::set<int>& robotnum = RigidBody::defaultRobotNumSet);
+  template <typename Scalar>
+  void doKinematics(KinematicsCache<Scalar>& cache, bool compute_JdotV = false) const {
```
Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: I feel like this one is too big to put in the header file (now I read:  you're asking the compiler to inline it).  And the explicit instantiations for it will be trivial (Scalar = double, Scalar = Autodiff, and eventually Scalar = TrigPoly)

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m [hunk 12]
```diff
@@ -70,6 +70,7 @@
 if ~isfield(options, 'compute_gradients'), options.compute_gradients = false; end
 if ~isfield(options, 'compute_JdotV'), options.compute_JdotV = ~isempty(v); end
 if ~isfield(options, 'force_new_kinsol'), options.force_new_kinsol = false; end
+if ~isfield(options, 'kinematics_cache_ptr_to_use'), options.kinematics_cache_ptr_to_use = []; end
```
Comment (RussTedrake) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: you definitely need to document this option.

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m [hunk 13]
```diff
@@ -83,7 +84,17 @@
 kinsol.v = v;
 
 if (options.use_mex && model.mex_model_ptr~=0 && isnumeric(q))
-  doKinematicsmex(model.mex_model_ptr,q,options.compute_gradients,v,options.compute_JdotV);
+  if isempty(options.kinematics_cache_ptr_to_use)
+    if options.compute_gradients
+      kinsol.mex_ptr = model.default_kinematics_cache_ptr_with_gradients;
```
Comment (RussTedrake) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: doesn't this break the contract?  If you're always overwriting the same existing kinematics cache object, then if I call 
```
kinsol = doKinematics(q1)
kinsol2 = doKinematics(q2)
```
are they going to be pointing to the same cache?

File: drake/systems/plants/RigidBodyManipulator.h [hunk 14]
```diff
@@ -97,46 +99,256 @@ class DLLEXPORT_RBM RigidBodyManipulator
...
+    cache.setJdotVCached(compute_JdotV && cache.hasV());
+  };
+
+  bool isBodyPartOfRobot(const RigidBody& body, const std::set<int>& robotnum) const;
+
+  double getMass(const std::set<int>& robotnum = RigidBody::defaultRobotNumSet) const;
 
   template <typename Scalar>
-  GradientVar<Scalar, SPACE_DIMENSION, 1> centerOfMass(int gradient_order, const std::set<int>& robotnum = RigidBody::defaultRobotNumSet);
+  GradientVar<Scalar, SPACE_DIMENSION, 1> centerOfMass(KinematicsCache<Scalar>& cache, int gradient_order, const std::set<int>& robotnum = RigidBody::defaultRobotNumSet) const;
```
Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: Nitpick:  The way that you are using this -- as a now mandatory argument for all of the kinematics functions, i don't really like the name KinematicsCache.  I think KinematicsSolution and kinsol would be more appropriate.  

Another organization that we could consider is having the KinematicsCache/Sol keep a pointer to the RBM, and then to actually move most of these methods over to the KinematicsCache class.  That would, I think, really be a cleaner interface.  
```
kinsol = doKinematics(q)
kinsol->forwardKin()
kinsol->centerOfMass()
...
```
That way you don't have to carry around both the kinsol and the rbm and pass them in together every time.  And it would safeguard against the possibility of someone passing a kinsol for the wrong RBM into these methods.

File: drake/systems/plants/RigidBodyManipulator.h [hunk 15]
```diff
@@ -250,38 +473,38 @@ class DLLEXPORT_RBM RigidBodyManipulator
...
+                                              const std::vector<Eigen::Vector3d>& points,
         double collision_threshold);
 
   void warnOnce(const std::string& id, const std::string& msg);
 
-  std::shared_ptr<RigidBody> findLink(std::string linkname, int robot=-1);
-  int findLinkId(std::string linkname, int robot = -1);
-  std::shared_ptr<RigidBody> findJoint(std::string jointname, int robot=-1);
-  int findJointId(std::string linkname, int robot = -1);
+  std::shared_ptr<RigidBody> findLink(std::string linkname, int robot=-1) const;
```
Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: nice.  keep those consts coming!

File: drake/systems/plants/allCollisionsmex.cpp [hunk 16]
```diff
@@ -14,16 +14,17 @@ using namespace std;
...
-    mexErrMsgIdAndTxt("Drake:collisionDetectmex:NotEnoughInputs","Usage collisionDetectmex(model_ptr)");
+  if (nrhs < 3) {
+    mexErrMsgIdAndTxt("Drake:allCollisions:NotEnoughInputs", "Usage allCollisionsmex(model_ptr, cache_ptr, active_collision_options)");
   }
 
-  // first get the model_ptr back from matlab
-  RigidBodyManipulator *model= (RigidBodyManipulator*) getDrakeMexPointer(prhs[0]);
+  int arg_num = 0;
+  RigidBodyManipulator *model = static_cast<RigidBodyManipulator*>(getDrakeMexPointer(prhs[arg_num++]));
+  KinematicsCache<double>* cache = static_cast<KinematicsCache<double>*>(getDrakeMexPointer(prhs[arg_num++]));
```
Comment (RussTedrake) [inline drake/systems/plants/allCollisionsmex.cpp]: changing to the kinsol-has-a-rbm version would simplify these, too.

Comment (RussTedrake) [inline drake/systems/plants/allCollisionsmex.cpp]: and it feels (to me) like the opportunity to get these mixed up coming from the matlab side is even more severe than from the c++ side.  the matlab side allocates a new rbm somewhat behind the scenes (during a compile), so if someone did
```
model = RigidBodyManipulator(...)
kinsol = doKinematics();
model = compile(model);  % which could happen inside methods which are not labeled as obviously as compile
model.forwardKin(kinsol, ...);
````
then we would have a problem.  Which makes me realize that my proposal, if we go for it, should really be implemented (eventually) on the matlab side, too.  But I'd prefer to have the c++ side clean first.  What do people think?

**Comment by tkoolen** [comment]
Re: failures on travis: yup, that was a mistake.

File: drake/systems/plants/RigidBodyManipulator.h (hunk 11 above)
Comment (tkoolen) [inline drake/systems/plants/RigidBodyManipulator.h]: OK, I can move this back if we must, although it's a pain when I experiment with different AutoDiffScalar types.

But what do you mean exactly by inlining in this case? There are a lot of overloaded usages of that word.

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 13 above)
Comment (tkoolen) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: The way I see it, I'm not breaking any of the existing Matlab code; the previous behavior of having the order of mex doKinematics calls matter is retained by default. However, you do now have the option of having the order of mex doKinematics calls *not* matter through the kinematics_cache_ptr_to_use option. So I'm adding a feature instead of breaking an existing contract. In the long run, it would be good to get rid of the default caches, but I didn't want to figure out what a good place to store the kinematics cache pointer is for every current use case of Matlab doKinematics.

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 12 above)
Comment (tkoolen) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: OK, will do.

**Comment by tkoolen** [comment]
Interesting error on travis: GCC, debug mode only, `g++-4.8: internal compiler error: Killed (program cc1plus)`

@rdeits, could this be GCC running out of memory?

File: drake/systems/plants/RigidBodyManipulator.h (hunk 11 above)
Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: by having the implementation in the header, you are asking the compiler to inline this function (as if you had put the inline tag in the method declaration).

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 13 above)
Comment (RussTedrake) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: i agree.  the previous code did not withhold the contract.  but now we can.

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 12 above)
Comment (tkoolen) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: but I haven't yet. I can do this real quick.

File: drake/systems/plants/RigidBodyManipulator.h (hunk 11 above)
Comment (tkoolen) [inline drake/systems/plants/RigidBodyManipulator.h]: Yes, but that doesn't mean that inline expansion will happen. This is my current understanding:
* the inline keyword doesn't actually command the compiler to use 'inline expansion' (i.e. putting the code of the function where the call happens, getting rid of the function call. At best, it's a suggestion to the compiler (https://msdn.microsoft.com/en-us/library/bw1hbe6y.aspx, https://isocpp.org/wiki/faq/Inline-Functions#overview-inline-fns). Whether or not the compiler will perform inline expansion depends on e.g. the size of the method.
* effects of the inline keyword on performance are very case-dependent (https://isocpp.org/wiki/faq/inline-functions#inline-and-perf)
* defining a method in the class body itself (in the header) automatically tells the compiler to make the method inline (as in, it does the same thing as adding the inline keyword) (https://isocpp.org/wiki/faq/Inline-Functions#inline-member-fns-more). This does *not* mean however that the compiler is forced to inline expand the code. It just follows the same rules as for any other function that is declared inline (https://stackoverflow.com/questions/5431362/how-does-templates-work-are-they-always-inlined)

Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: yes.  totally know and understand.  but i think it’s bad form to ask the compiler to inline and have it reject you (maybe, depending on the compiler).

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 13 above)
Comment (tkoolen) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: So should the default behavior be to create a new KinematicsCache every time you call doKinematics? That's very slow...

Comment (RussTedrake) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: I think it has to be?  Or somehow pass-by-value an existing one?

File: drake/systems/plants/RigidBodyManipulator.h (hunk 14 above)
Comment (tkoolen) [inline drake/systems/plants/RigidBodyManipulator.h]: I don't really like either name actually. The Kinematics part isn't really accurate. As far as Cache vs. Solution, I like Cache slightly better, but not super opinionated either way.

As for moving all of the methods from RBM to Kinematics*, that kind of makes sense. @patmarion mentioned that too. I'd like to do it in a future pull request though (and might abondon it if I run into unforseen trouble).

Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: > I don't really like either name actually. The Kinematics part isn't really accurate. As far as Cache vs. Solution, I like Cache slightly better, but not super opinionated either way.
> 
I'm also ok, but would vote for Solution.  I don’t love it, but don’t feel like Cache is right.
> As for moving all of the methods from RBM to Kinematics*, that kind of makes sense. @patmarion <https://github.com/patmarion> mentioned that too. I'd like to do it in a future pull request though (and might abondon it if I run into unforseen trouble).
> 
Sounds perfect

File: drake/systems/plants/RigidBodyManipulator.h (hunk 11 above)
Comment (tkoolen) [inline drake/systems/plants/RigidBodyManipulator.h]: But then isn't it equally bad form to not add an inline keyword while the compiler does decide to perform inline expansion? And how do I get feedback from the compiler to know if I was right ;-)

Comment (RussTedrake) [inline drake/systems/plants/RigidBodyManipulator.h]: do you mean because it’s a class method in the header?  in my mind that is the same as writing the inline keyword.

Comment (tkoolen) [inline drake/systems/plants/RigidBodyManipulator.h]: I was referring to the fact that compilers are also free to use inline expansion for any function that's not marked inline.
Defining a method in the class body itself (in the header) does the same thing as adding the inline keyword, yes, but as I said that's not the same thing as forcing the compiler to perform inline expansion.

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 12 above)
Comment (tkoolen) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: done.

**Comment by tkoolen** [comment]
Now it's clang in debug mode, `clang: error: unable to execute command: Killed`. I would guess it's just running out of memory.

File: drake/systems/plants/@RigidBodyManipulator/doKinematics.m (hunk 13 above)
Comment (tkoolen) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: Fixing things on the Matlab side is not the main objective of this pull request. In fact, I actively tried to avoid making major changes in Matlab, I just want to keep it working as is. Requiring that the caller passes in an existing one means I have to change all usages of doKinematics in Matlab and find a place to store a kinematics cache to reuse. Creating a new DrakeMexPointer to KinematicsCache makes everything much slower.

Comment (RussTedrake) [inline drake/systems/plants/@RigidBodyManipulator/doKinematics.m]: right, i think that we would need a cache (of size one) so that it returns the same kinsol ptr if doKinematics is called with exactly the same arguments.  We’ve used that as the contract everywhere — it’s ok to call doKinematics locally because it will return quickly after the first hit.

I’m ok accepting as is.

**Comment by rdeits** [comment]
@tkoolen I've been seeing travis fail in debug mode recently. I assume it's a memory issue, see: http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error
