### PR TITLE
Fixes observers and adds a test case

### LINKED ISSUE #1195: Observers aren't working
None of the unit tests or examples are hitting the code in systems/observers and it looks like it might have gone stale.

I tried using it but there are a few syntax errors that are preventing it from working.  I'll give it some love when I get the chance.

### PR DESCRIPTION
**Pull request by psiorx**
This brings the stale observer code back online and provides an example of observer-based state feedback control in the form of balancing a two wheeled inverted pendulum (TWIP).  

Resolves #1195 

The dynamics of the two wheeled inverted pendulum are similar to the cartpole, but different in the sense that the torque provided to the wheels by the motor also induces a counter-torque on the body.  This makes it more difficult to stabilize and swing-up.

Swing-up video:
https://youtu.be/w8lUvj6dZMA

### CODE REVIEW

File: drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+%construct LQR controller
+controller = r.balanceLQR();
+
+%wire up the system
+sysCl = buildClosedLoopObserverControl(r, observer, controller);
+
+xtraj = sysCl.simulate([0, 5]);
+v.playback(xtraj)
+
+function sysCl = buildClosedLoopObserverControl(plant, observer, controller)
```
Comment (psiorx) [inline drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m]: This is a little gross but I didn't see a better way to do it.  This could probably be made more general and/or pulled into the observer framework.

Comment (RussTedrake) [inline drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m]: yikes.  agreed that we should put this functionality up in the observer class at some point, and that it's ok to do it locally first.  but i think it's important to maintain the abstract above simulink (so we don't depend on it, for instance). 

i think you could do the same thing with a call to mimoCascade, then mimoFeedback.  e.g. 
```
mimoFeedback(mimoCascade(plant,observer),controller)
```
i hope that the auto-wiring would work here (probably we should make it work if it doesn't)

File: drake/examples/TwoWheeledInvertedPendulum/TWIP.m [hunk 2]
```diff
@@ -0,0 +1,145 @@
+classdef TWIP < DrakeSystem 
+
```
Comment (RussTedrake) [inline drake/examples/TwoWheeledInvertedPendulum/TWIP.m]: add a description (like what you have here:
The dynamics of the two wheeled inverted pendulum are similar to the cartpole, but different in the sense that the torque provided to the wheels by the motor also induces a counter-torque on the body. This makes it more difficult to stabilize and swing-up. )

**Comment by RussTedrake** [comment]
otherwise, looks good. 
out of curiousity, why did you add TWIP for this, instead of making it work for one of the existing examples?

**Comment by psiorx** [comment]
I chose to use the TWIP instead of an existing example for a few reasons:

 * I had the dynamics and parameters on hand from a personal project so adding it didn't involve much work
 * Most (all?) of the other examples use full state output and I didn't want to break their control examples
 * I had already done the observer design and just needed to fit it in the Drake framework
 * It's cool to have a segway in Drake :)

File: drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m (hunk 1 above)
Comment (psiorx) [inline drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m]: I'd love to get this working with the existing composition methods but I tried a few ways of calling mimoCascade/mimoFeedback and none of them did exactly what I wanted.

I need both the input and output of the plant to be wired to just the input of the observer.

The desired configuration is shown by this block diagram:

observerblockdiagram

If I run mimoCascade(plant, observer), I get back a model that has this input frame:

```MATLAB
Multi-Coordinate Frame: TWIPInput+TWIPInput (2 elements)
  TWIPInput (1 elements)
  TWIPInput (1 elements)

I'm not sure why the input frame is duplicated but that doesn't seem right.

Comment (RussTedrake) [inline drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m]: just sent a pull request with a solution.

while I admit it is not great, the mimoCascade call you made is actually doing exactly the right thing (given the documented interface) by creating the duplicated input frame.

Comment (psiorx) [inline drake/examples/TwoWheeledInvertedPendulum/runObserverControl.m]: Thanks for clearing that up.  I think the new default is a lot cleaner.
